local vehs = {
	["blista"] = { ['name'] = "Blista", ['price'] = 13500, ['type'] = "carros" },
	["brioso"] = { ['name'] = "Brioso", ['price'] = 17000, ['type'] = "carros" },
	["emperor"] = { ['name'] = "Emperor", ['price'] = 50000, ['type'] = "carros" },
	["emperor2"] = { ['name'] = "Emperor 2", ['price'] = 50000, ['type'] = "carros" },
	["dilettante"] = { ['name'] = "Dilettante", ['price'] = 45700, ['type'] = "carros" },
	["issi2"] = { ['name'] = "Issi2", ['price'] = 61850, ['type'] = "carros" },
	["panto"] = { ['name'] = "Panto", ['price'] = 5000, ['type'] = "carros" },
	["savestra"] = { ['name'] = "Savestra", ['price'] = 63500, ['type'] = "carros" },
	["prairie"] = { ['name'] = "Prairie", ['price'] = 23150, ['type'] = "carros" },
	["rhapsody"] = { ['name'] = "Rhapsody", ['price'] = 7000, ['type'] = "carros" },
	["cogcabrio"] = { ['name'] = "Cogcabrio", ['price'] = 130000, ['type'] = "carros" },
	["exemplar"] = { ['name'] = "Exemplar", ['price'] = 80000, ['type'] = "carros" },
	["f620"] = { ['name'] = "F620", ['price'] = 55000, ['type'] = "carros" },
	["felon"] = { ['name'] = "Felon", ['price'] = 70000, ['type'] = "carros" },
	["ingot"] = { ['name'] = "Ingot", ['price'] = 160000, ['type'] = "carros" },
	["jackal"] = { ['name'] = "Jackal", ['price'] = 60000, ['type'] = "carros" },
	["oracle"] = { ['name'] = "Oracle", ['price'] = 60000, ['type'] = "carros" },
	["oracle2"] = { ['name'] = "Oracle2", ['price'] = 80000, ['type'] = "carros" },
	["sentinel"] = { ['name'] = "Sentinel", ['price'] = 50000, ['type'] = "carros" },
	["sentinel2"] = { ['name'] = "Sentinel2", ['price'] = 65000, ['type'] = "carros" },
	["windsor"] = { ['name'] = "Windsor", ['price'] = 150000, ['type'] = "carros" },
	["windsor2"] = { ['name'] = "Windsor2", ['price'] = 170000, ['type'] = "carros" },
	["zion"] = { ['name'] = "Zion", ['price'] = 50000, ['type'] = "carros" },
	["zion2"] = { ['name'] = "Zion2", ['price'] = 60000, ['type'] = "carros" },
	["blade"] = { ['name'] = "Blade", ['price'] = 110000, ['type'] = "carros" },
	["buccaneer"] = { ['name'] = "Buccaneer", ['price'] = 115000, ['type'] = "carros" },
	["buccaneer2"] = { ['name'] = "Buccaneer2", ['price'] = 160000, ['type'] = "carros" },
	["primo"] = { ['name'] = "Primo", ['price'] = 60000, ['type'] = "carros" },
	["chino"] = { ['name'] = "Chino", ['price'] = 130000, ['type'] = "carros" },
	["coquette3"] = { ['name'] = "Coquette3", ['price'] = 195000, ['type'] = "carros" },
	["dukes"] = { ['name'] = "Dukes", ['price'] = 150000, ['type'] = "carros" },
	["faction"] = { ['name'] = "Faction", ['price'] = 150000, ['type'] = "carros" },
	["faction3"] = { ['name'] = "Faction3", ['price'] = 350000, ['type'] = "carros" },
	["gauntlet"] = { ['name'] = "Gauntlet", ['price'] = 100000, ['type'] = "carros" },
	["gauntlet2"] = { ['name'] = "Gauntlet2", ['price'] = 165000, ['type'] = "carros" },
	["hermes"] = { ['name'] = "Hermes", ['price'] = 280000, ['type'] = "carros" },
	["hotknife"] = { ['name'] = "Hotknife", ['price'] = 180000, ['type'] = "carros" },
	["moonbeam"] = { ['name'] = "Moonbeam", ['price'] = 220000, ['type'] = "carros" },
	["moonbeam2"] = { ['name'] = "Moonbeam2", ['price'] = 250000, ['type'] = "carros" },
	["nightshade"] = { ['name'] = "Nightshade", ['price'] = 270000, ['type'] = "carros" },
	["picador"] = { ['name'] = "Picador", ['price'] = 150000, ['type'] = "carros" },
	["ruiner"] = { ['name'] = "Ruiner", ['price'] = 150000, ['type'] = "carros" },
	["sabregt"] = { ['name'] = "Sabregt", ['price'] = 260000, ['type'] = "carros" },
	["sabregt2"] = { ['name'] = "Sabregt2", ['price'] = 150000, ['type'] = "carros" },
	["slamvan"] = { ['name'] = "Slamvan", ['price'] = 180000, ['type'] = "carros" },
	["slamvan3"] = { ['name'] = "Slamvan3", ['price'] = 230000, ['type'] = "carros" },
	["stalion"] = { ['name'] = "Stalion", ['price'] = 150000, ['type'] = "carros" },
	["stalion2"] = { ['name'] = "Stalion2", ['price'] = 150000, ['type'] = "carros" },
	["tampa"] = { ['name'] = "Tampa", ['price'] = 170000, ['type'] = "carros" },
	["vigero"] = { ['name'] = "Vigero", ['price'] = 170000, ['type'] = "carros" },
	["virgo"] = { ['name'] = "Virgo", ['price'] = 150000, ['type'] = "carros" },
	["virgo2"] = { ['name'] = "Virgo2", ['price'] = 250000, ['type'] = "carros" },
	["virgo3"] = { ['name'] = "Virgo3", ['price'] = 180000, ['type'] = "carros" },
	["voodoo"] = { ['name'] = "Voodoo", ['price'] = 220000, ['type'] = "carros" },
	["voodoo2"] = { ['name'] = "Voodoo2", ['price'] = 220000, ['type'] = "carros" },
	["yosemite"] = { ['name'] = "Yosemite", ['price'] = 350000, ['type'] = "carros" },
	["bfinjection"] = { ['name'] = "Bfinjection", ['price'] = 80000, ['type'] = "carros" },
	["bifta"] = { ['name'] = "Bifta", ['price'] = 61830, ['type'] = "carros" },
	["bodhi2"] = { ['name'] = "Bodhi2", ['price'] = 170000, ['type'] = "carros" },
	["brawler"] = { ['name'] = "Brawler", ['price'] = 250000, ['type'] = "carros" },
	["trophytruck"] = { ['name'] = "Trophytruck", ['price'] = 400000, ['type'] = "carros" },
	["trophytruck2"] = { ['name'] = "Trophytruck2", ['price'] = 400000, ['type'] = "carros" },
	["dubsta3"] = { ['name'] = "Dubsta3", ['price'] = 300000, ['type'] = "carros" },
	["mesa3"] = { ['name'] = "Mesa3", ['price'] = 200000, ['type'] = "carros" },
	["rancherxl"] = { ['name'] = "Rancherxl", ['price'] = 220000, ['type'] = "carros" },
	["rebel2"] = { ['name'] = "Rebel2", ['price'] = 250000, ['type'] = "carros" },
	["riata"] = { ['name'] = "Riata", ['price'] = 250000, ['type'] = "carros" },
	["dloader"] = { ['name'] = "Dloader", ['price'] = 150000, ['type'] = "carros" },
	["sandking"] = { ['name'] = "Sandking", ['price'] = 200000, ['type'] = "carros" },
	["sandking2"] = { ['name'] = "Sandking2", ['price'] = 235000, ['type'] = "carros" },
	["baller"] = { ['name'] = "Baller", ['price'] = 150000, ['type'] = "carros" },
	["baller2"] = { ['name'] = "Baller2", ['price'] = 160000, ['type'] = "carros" },
	["baller3"] = { ['name'] = "Baller3", ['price'] = 175000, ['type'] = "carros" },
	["baller4"] = { ['name'] = "Baller4", ['price'] = 185000, ['type'] = "carros" },
	["baller5"] = { ['name'] = "Baller5", ['price'] = 270000, ['type'] = "carros" },
	["baller6"] = { ['name'] = "Baller6", ['price'] = 280000, ['type'] = "carros" },
	["bjxl"] = { ['name'] = "Bjxl", ['price'] = 110000, ['type'] = "carros" },
	["cavalcade"] = { ['name'] = "Cavalcade", ['price'] = 110000, ['type'] = "carros" },
	["cavalcade2"] = { ['name'] = "Cavalcade2", ['price'] = 130000, ['type'] = "carros" },
	["contender"] = { ['name'] = "Contender", ['price'] = 125000, ['type'] = "carros" },
	["dubsta"] = { ['name'] = "Dubsta", ['price'] = 210000, ['type'] = "carros" },
	["dubsta2"] = { ['name'] = "Dubsta2", ['price'] = 240000, ['type'] = "carros" },
	["fq2"] = { ['name'] = "Fq2", ['price'] = 110000, ['type'] = "carros" },
	["granger"] = { ['name'] = "Granger", ['price'] = 345000, ['type'] = "carros" },
	["gresley"] = { ['name'] = "Gresley", ['price'] = 150000, ['type'] = "carros" },
	["habanero"] = { ['name'] = "Habanero", ['price'] = 110000, ['type'] = "carros" },
	["seminole"] = { ['name'] = "Seminole", ['price'] = 110000, ['type'] = "carros" },
	["serrano"] = { ['name'] = "Serrano", ['price'] = 150000, ['type'] = "carros" },
	["xls"] = { ['name'] = "Xls", ['price'] = 150000, ['type'] = "carros" },
	["xls2"] = { ['name'] = "Xls2", ['price'] = 350000, ['type'] = "carros" },
	["asea"] = { ['name'] = "Asea", ['price'] = 55000, ['type'] = "carros" },
	["asterope"] = { ['name'] = "Asterope", ['price'] = 65000, ['type'] = "carros" },
	["cog552"] = { ['name'] = "Cog552", ['price'] = 400000, ['type'] = "carros" },
	["cognoscenti"] = { ['name'] = "Cognoscenti", ['price'] = 280000, ['type'] = "carros" },
	["cognoscenti2"] = { ['name'] = "Cognoscenti2", ['price'] = 400000, ['type'] = "carros" },
	["stanier"] = { ['name'] = "Stanier", ['price'] = 10000, ['type'] = "carros" },
	["stratum"] = { ['name'] = "Stratum", ['price'] = 90000, ['type'] = "carros" },
	["surge"] = { ['name'] = "Surge", ['price'] = 110000, ['type'] = "carros" },
	["tailgater"] = { ['name'] = "Tailgater", ['price'] = 110000, ['type'] = "carros" },
	["warrener"] = { ['name'] = "Warrener", ['price'] = 90000, ['type'] = "carros" },
	["washington"] = { ['name'] = "Washington", ['price'] = 130000, ['type'] = "carros" },
	["alpha"] = { ['name'] = "Alpha", ['price'] = 230000, ['type'] = "carros" },
	["banshee"] = { ['name'] = "Banshee", ['price'] = 300000, ['type'] = "carros" },
	["bestiagts"] = { ['name'] = "Bestiagts", ['price'] = 200000, ['type'] = "carros" },
	["blista2"] = { ['name'] = "Blista2", ['price'] = 55000, ['type'] = "carros" },
	["blista3"] = { ['name'] = "Blista3", ['price'] = 80000, ['type'] = "carros" },
	["buffalo"] = { ['name'] = "Buffalo", ['price'] = 300000, ['type'] = "carros" },
	["buffalo2"] = { ['name'] = "Buffalo2", ['price'] = 300000, ['type'] = "carros" },
	["buffalo3"] = { ['name'] = "Buffalo3", ['price'] = 300000, ['type'] = "carros" },
	["carbonizzare"] = { ['name'] = "Carbonizzare", ['price'] = 290000, ['type'] = "carros" },
	["comet2"] = { ['name'] = "Comet2", ['price'] = 250000, ['type'] = "carros" },
	["comet3"] = { ['name'] = "Comet3", ['price'] = 290000, ['type'] = "carros" },
	["comet5"] = { ['name'] = "Comet5", ['price'] = 300000, ['type'] = "carros" },
	["coquette"] = { ['name'] = "Coquette", ['price'] = 250000, ['type'] = "carros" },
	["elegy"] = { ['name'] = "Elegy", ['price'] = 350000, ['type'] = "carros" },
	["elegy2"] = { ['name'] = "Elegy2", ['price'] = 355000, ['type'] = "carros" },
	["feltzer2"] = { ['name'] = "Feltzer2", ['price'] = 255000, ['type'] = "carros" },
	["furoregt"] = { ['name'] = "Furoregt", ['price'] = 290000, ['type'] = "carros" },
	["fusilade"] = { ['name'] = "Fusilade", ['price'] = 210000, ['type'] = "carros" },
	["futo"] = { ['name'] = "Futo", ['price'] = 170000, ['type'] = "carros" },
	["jester"] = { ['name'] = "Jester", ['price'] = 138000, ['type'] = "carros" },
	["khamelion"] = { ['name'] = "Khamelion", ['price'] = 210000, ['type'] = "carros" },
	["kuruma"] = { ['name'] = "Kuruma", ['price'] = 170000, ['type'] = "carros" },
	["massacro"] = { ['name'] = "Massacro", ['price'] = 330000, ['type'] = "carros" },
	["massacro2"] = { ['name'] = "Massacro2", ['price'] = 330000, ['type'] = "carros" },
	["ninef"] = { ['name'] = "Ninef", ['price'] = 125000, ['type'] = "carros" },
	["ninef2"] = { ['name'] = "Ninef2", ['price'] = 140000, ['type'] = "carros" },
	["omnis"] = { ['name'] = "Omnis", ['price'] = 240000, ['type'] = "carros" },
	["pariah"] = { ['name'] = "Pariah", ['price'] = 500000, ['type'] = "carros" },
	["penumbra"] = { ['name'] = "Penumbra", ['price'] = 150000, ['type'] = "carros" },
	["raiden"] = { ['name'] = "Raiden", ['price'] = 240000, ['type'] = "carros" },
	["rapidgt"] = { ['name'] = "Rapidgt", ['price'] = 200000, ['type'] = "carros" },
	["rapidgt2"] = { ['name'] = "Rapidgt2", ['price'] = 300000, ['type'] = "carros" },
	["ruston"] = { ['name'] = "Ruston", ['price'] = 370000, ['type'] = "carros" },
	["schafter3"] = { ['name'] = "Schafter3", ['price'] = 275000, ['type'] = "carros" },
	["schafter4"] = { ['name'] = "Schafter4", ['price'] = 125000, ['type'] = "carros" },
	["schafter5"] = { ['name'] = "Schafter5", ['price'] = 275000, ['type'] = "carros" },
	["schwarzer"] = { ['name'] = "Schwarzer", ['price'] = 170000, ['type'] = "carros" },
	["sentinel3"] = { ['name'] = "Sentinel3", ['price'] = 89000, ['type'] = "carros" },
	["seven70"] = { ['name'] = "Seven70", ['price'] = 370000, ['type'] = "carros" },
	["specter"] = { ['name'] = "Specter", ['price'] = 320000, ['type'] = "carros" },
	["specter2"] = { ['name'] = "Specter2", ['price'] = 355000, ['type'] = "carros" },
	["streiter"] = { ['name'] = "Streiter", ['price'] = 250000, ['type'] = "carros" },
	["sultan"] = { ['name'] = "Sultan", ['price'] = 210000, ['type'] = "carros" },
	["surano"] = { ['name'] = "Surano", ['price'] = 300500, ['type'] = "carros" },
	["tampa2"] = { ['name'] = "Tampa2", ['price'] = 200000, ['type'] = "carros" },
	["tropos"] = { ['name'] = "Tropos", ['price'] = 170000, ['type'] = "carros" },
	["verlierer2"] = { ['name'] = "Verlierer2", ['price'] = 380000, ['type'] = "carros" },
	["btype2"] = { ['name'] = "Btype2", ['price'] = 460000, ['type'] = "carros" },
	["btype3"] = { ['name'] = "Btype3", ['price'] = 60500, ['type'] = "carros" },
	["casco"] = { ['name'] = "Casco", ['price'] = 355000, ['type'] = "carros" },
	["cheetah"] = { ['name'] = "Cheetah", ['price'] = 425000, ['type'] = "carros" },
	["coquette2"] = { ['name'] = "Coquette2", ['price'] = 285000, ['type'] = "carros" },
	["feltzer3"] = { ['name'] = "Feltzer3", ['price'] = 220000, ['type'] = "carros" },
	["gt500"] = { ['name'] = "Gt500", ['price'] = 250000, ['type'] = "carros" },
	["infernus2"] = { ['name'] = "Infernus2", ['price'] = 250000, ['type'] = "carros" },
	["jb700"] = { ['name'] = "Jb700", ['price'] = 220000, ['type'] = "carros" },
	["mamba"] = { ['name'] = "Mamba", ['price'] = 300000, ['type'] = "carros" },
	["manana"] = { ['name'] = "Manana", ['price'] = 130000, ['type'] = "carros" },
	["monroe"] = { ['name'] = "Monroe", ['price'] = 260000, ['type'] = "carros" },
	["peyote"] = { ['name'] = "Peyote", ['price'] = 150000, ['type'] = "carros" },
	["pigalle"] = { ['name'] = "Pigalle", ['price'] = 250000, ['type'] = "carros" },
	["rapidgt3"] = { ['name'] = "Rapidgt3", ['price'] = 123000, ['type'] = "carros" },
	["retinue"] = { ['name'] = "Retinue", ['price'] = 150000, ['type'] = "carros" },
	["stinger"] = { ['name'] = "Stinger", ['price'] = 220000, ['type'] = "carros" },
	["stingergt"] = { ['name'] = "Stingergt", ['price'] = 230000, ['type'] = "carros" },
	["torero"] = { ['name'] = "Torero", ['price'] = 160000, ['type'] = "carros" },
	["issi6"] = { ['name'] = "Issi 6", ['price'] = 60000, ['type'] = "carros" },
	["tornado"] = { ['name'] = "Tornado", ['price'] = 150000, ['type'] = "carros" },
	["tornado2"] = { ['name'] = "Tornado2", ['price'] = 160000, ['type'] = "carros" },
	["tornado6"] = { ['name'] = "Tornado6", ['price'] = 250000, ['type'] = "carros" },
	["turismo2"] = { ['name'] = "Turismo2", ['price'] = 250000, ['type'] = "carros" },
	["ztype"] = { ['name'] = "Ztype", ['price'] = 400000, ['type'] = "carros" },
	["adder"] = { ['name'] = "Adder", ['price'] = 620000, ['type'] = "carros" },
	["banshee2"] = { ['name'] = "Banshee2", ['price'] = 370000, ['type'] = "carros" },
	["bullet"] = { ['name'] = "Bullet", ['price'] = 400000, ['type'] = "carros" },
	["cheetah2"] = { ['name'] = "Cheetah2", ['price'] = 240000, ['type'] = "carros" },
	["entityxf"] = { ['name'] = "Entityxf", ['price'] = 460000, ['type'] = "carros" },
	["fmj"] = { ['name'] = "Fmj", ['price'] = 520000, ['type'] = "carros" },
	["gp1"] = { ['name'] = "Gp1", ['price'] = 495000, ['type'] = "carros" },
	["infernus"] = { ['name'] = "Infernus", ['price'] = 470000, ['type'] = "carros" },
	["nero"] = { ['name'] = "Nero", ['price'] = 450000, ['type'] = "carros" },
	["nero2"] = { ['name'] = "Nero2", ['price'] = 480000, ['type'] = "carros" },
	["penetrator"] = { ['name'] = "Penetrator", ['price'] = 480000, ['type'] = "carros" },
	["pfister811"] = { ['name'] = "Pfister811", ['price'] = 530000, ['type'] = "carros" },
	["reaper"] = { ['name'] = "Reaper", ['price'] = 620000, ['type'] = "carros" },
	["sc1"] = { ['name'] = "Sc1", ['price'] = 495000, ['type'] = "carros" },
	["t20"] = { ['name'] = "T20", ['price'] = 670000, ['type'] = "carros" },
	["tempesta"] = { ['name'] = "Tempesta", ['price'] = 600000, ['type'] = "carros" },
	["turismor"] = { ['name'] = "Turismor", ['price'] = 620000, ['type'] = "carros" },
	["vacca"] = { ['name'] = "Vacca", ['price'] = 620000, ['type'] = "carros" },
	["voltic"] = { ['name'] = "Voltic", ['price'] = 440000, ['type'] = "carros" },
	["zentorno"] = { ['name'] = "Zentorno", ['price'] = 920000, ['type'] = "carros" },
	["sadler"] = { ['name'] = "Sadler", ['price'] = 180000, ['type'] = "carros" },
	["bison"] = { ['name'] = "Bison", ['price'] = 220000, ['type'] = "carros" },
	["bison2"] = { ['name'] = "Bison2", ['price'] = 180000, ['type'] = "carros" },
	["bobcatxl"] = { ['name'] = "Bobcatxl", ['price'] = 260000, ['type'] = "carros" },
	["burrito"] = { ['name'] = "Burrito", ['price'] = 200000, ['type'] = "carros" },
	["burrito2"] = { ['name'] = "Burrito2", ['price'] = 150000, ['type'] = "carros" },
	["burrito3"] = { ['name'] = "Burrito3", ['price'] = 260000, ['type'] = "carros" },
	["burrito4"] = { ['name'] = "Burrito4", ['price'] = 260000, ['type'] = "carros" },
	["mule4"] = { ['name'] = "Burrito4", ['price'] = 260000, ['type'] = "carros" },
	["rallytruck"] = { ['name'] = "Burrito4", ['price'] = 260000, ['type'] = "carros" },
	["minivan"] = { ['name'] = "Minivan", ['price'] = 110000, ['type'] = "carros" },
	["minivan2"] = { ['name'] = "Minivan2", ['price'] = 220000, ['type'] = "carros" },
	["paradise"] = { ['name'] = "Paradise", ['price'] = 260000, ['type'] = "carros" },
	["pony"] = { ['name'] = "Pony", ['price'] = 260000, ['type'] = "carros" },
	["pony2"] = { ['name'] = "Pony2", ['price'] = 260000, ['type'] = "carros" },
	["rumpo"] = { ['name'] = "Rumpo", ['price'] = 100000, ['type'] = "carros" },
	["rumpo2"] = { ['name'] = "Rumpo2", ['price'] = 260000, ['type'] = "carros" },
	["rumpo3"] = { ['name'] = "Rumpo3", ['price'] = 350000, ['type'] = "carros" },
	["surfer"] = { ['name'] = "Surfer", ['price'] = 55000, ['type'] = "carros" },
	["youga"] = { ['name'] = "Youga", ['price'] = 260000, ['type'] = "carros" },
	["huntley"] = { ['name'] = "Huntley", ['price'] = 110000, ['type'] = "carros" },
	["landstalker"] = { ['name'] = "Landstalker", ['price'] = 130000, ['type'] = "carros" },
	["mesa"] = { ['name'] = "Mesa", ['price'] = 90000, ['type'] = "carros" },
	["patriot"] = { ['name'] = "Patriot", ['price'] = 250000, ['type'] = "carros" },
	["radi"] = { ['name'] = "Radi", ['price'] = 110000, ['type'] = "carros" },
	["rocoto"] = { ['name'] = "Rocoto", ['price'] = 110000, ['type'] = "carros" },
	["tyrant"] = { ['name'] = "Tyrant", ['price'] = 690000, ['type'] = "carros" },
	["cheburek"] = { ['name'] = "Cheburek", ['price'] = 170000, ['type'] = "carros" },
	["hotring"] = { ['name'] = "Hotring", ['price'] = 300000, ['type'] = "carros" },
	["jester3"] = { ['name'] = "Jester3", ['price'] = 345000, ['type'] = "carros" },
	["flashgt"] = { ['name'] = "Flashgt", ['price'] = 370000, ['type'] = "carros" },
	["ellie"] = { ['name'] = "Ellie", ['price'] = 100000, ['type'] = "carros" },
	["michelli"] = { ['name'] = "Michelli", ['price'] = 160000, ['type'] = "carros" },
	["fagaloa"] = { ['name'] = "Fagaloa", ['price'] = 320000, ['type'] = "carros" },
	["dominator"] = { ['name'] = "Dominator", ['price'] = 93000, ['type'] = "carros" },
	["dominator2"] = { ['name'] = "Dominator2", ['price'] = 230000, ['type'] = "carros" },
	["dominator3"] = { ['name'] = "Dominator3", ['price'] = 105000, ['type'] = "carros" },
	["issi3"] = { ['name'] = "Issi3", ['price'] = 190000, ['type'] = "carros" },
	["taipan"] = { ['name'] = "Taipan", ['price'] = 620000, ['type'] = "carros" },
	["gb200"] = { ['name'] = "Gb200", ['price'] = 195000, ['type'] = "carros" },
	["stretch"] = { ['name'] = "Stretch", ['price'] = 1500000, ['type'] = "carros" },
	["guardian"] = { ['name'] = "Guardian", ['price'] = 385000, ['type'] = "carros" },
	["kamacho"] = { ['name'] = "Kamacho", ['price'] = 460000, ['type'] = "carros" },
	["cyclone"] = { ['name'] = "Cyclone", ['price'] = 920000, ['type'] = "carros" },
	["italigtb"] = { ['name'] = "Italigtb", ['price'] = 600000, ['type'] = "carros" },
	["italigtb2"] = { ['name'] = "Italigtb2", ['price'] = 610000, ['type'] = "carros" },
	["vagner"] = { ['name'] = "Vagner", ['price'] = 680000, ['type'] = "carros" },
	["xa21"] = { ['name'] = "Xa21", ['price'] = 630000, ['type'] = "carros" },
	["tezeract"] = { ['name'] = "Tezeract", ['price'] = 920000, ['type'] = "carros" },
	["prototipo"] = { ['name'] = "Prototipo", ['price'] = 1030000, ['type'] = "carros" },
	["patriot2"] = { ['name'] = "Patriot2", ['price'] = 550000, ['type'] = "carros" },
	["swinger"] = { ['name'] = "Swinger", ['price'] = 250000, ['type'] = "carros" },
	["clique"] = { ['name'] = "Clique", ['price'] = 360000, ['type'] = "carros" },
	["deveste"] = { ['name'] = "Deveste", ['price'] = 920000, ['type'] = "carros" },
	["deviant"] = { ['name'] = "Deviant", ['price'] = 370000, ['type'] = "carros" },
	["impaler"] = { ['name'] = "Impaler", ['price'] = 170000, ['type'] = "carros" },
	["italigto"] = { ['name'] = "Italigto", ['price'] = 485000, ['type'] = "carros" },
	["toros"] = { ['name'] = "Toros", ['price'] = 210000, ['type'] = "carros" },
	["tulip"] = { ['name'] = "Tulip", ['price'] = 114000, ['type'] = "carros" },
	["vamos"] = { ['name'] = "Vamos", ['price'] = 110000, ['type'] = "carros" },
	["freecrawler"] = { ['name'] = "Freecrawler", ['price'] = 300000, ['type'] = "carros" },
	["fugitive"] = { ['name'] = "Fugitive", ['price'] = 50000, ['type'] = "carros" },
	["glendale"] = { ['name'] = "Glendale", ['price'] = 70000, ['type'] = "carros" },
	["intruder"] = { ['name'] = "Intruder", ['price'] = 60000, ['type'] = "carros" },
	["le7b"] = { ['name'] = "Le7b", ['price'] = 700000, ['type'] = "carros" },
	["lurcher"] = { ['name'] = "Lurcher", ['price'] = 150000, ['type'] = "carros" },
	["lynx"] = { ['name'] = "Lynx", ['price'] = 370000, ['type'] = "carros" },
	["phoenix"] = { ['name'] = "Phoenix", ['price'] = 250000, ['type'] = "carros" },
	["premier"] = { ['name'] = "Premier", ['price'] = 35000, ['type'] = "carros" },
	["raptor"] = { ['name'] = "Raptor", ['price'] = 300000, ['type'] = "carros" },
	["sheava"] = { ['name'] = "Sheava", ['price'] = 700000, ['type'] = "carros" },
	["z190"] = { ['name'] = "Z190", ['price'] = 350000, ['type'] = "carros" },
	["benson"] = { ['name'] = "Benson", ['price'] = 500000, ['type'] = "carros" },
	["hilux2019"] = { ['name'] = "Hilux 2019", ['price'] = 150000, ['type'] = "carros" },

	--MOTOS
	
	["akuma"] = { ['name'] = "Akuma", ['price'] = 350000, ['type'] = "motos" },
	["avarus"] = { ['name'] = "Avarus", ['price'] = 123000, ['type'] = "motos" },
	["bagger"] = { ['name'] = "Bagger", ['price'] = 300000, ['type'] = "motos" },
	["bati"] = { ['name'] = "Bati", ['price'] = 370000, ['type'] = "motos" },
	["bati2"] = { ['name'] = "Bati2", ['price'] = 300000, ['type'] = "motos" },
	["bf400"] = { ['name'] = "Bf400", ['price'] = 105000, ['type'] = "motos" },
	["carbonrs"] = { ['name'] = "Carbonrs", ['price'] = 370000, ['type'] = "motos" },
	["chimera"] = { ['name'] = "Chimera", ['price'] = 345000, ['type'] = "motos" },
	["cliffhanger"] = { ['name'] = "Cliffhanger", ['price'] = 390000, ['type'] = "motos" },
	["daemon2"]  = { ['name'] = "Daemon2", ['price'] = 105000, ['type'] = "motos" },
	["defiler"] = { ['name'] = "Defiler", ['price'] = 460000, ['type'] = "motos" },
	["diablous"] = { ['name'] = "Diablous", ['price'] = 205000, ['type'] = "motos" },
	["diablous2"] = { ['name'] = "Diablous2", ['price'] = 460000, ['type'] = "motos" },
	["double"] = { ['name'] = "Double", ['price'] = 123000, ['type'] = "motos" },
	["enduro"] = { ['name'] = "Enduro", ['price'] = 30000, ['type'] = "motos" },
	["esskey"] = { ['name'] = "Esskey", ['price'] = 30000, ['type'] = "motos" },
	["faggio"] = { ['name'] = "Faggio", ['price'] = 3000, ['type'] = "motos" },
	["faggio2"] = { ['name'] = "Faggio2", ['price'] = 5000, ['type'] = "motos" },
	["faggio3"] = { ['name'] = "Faggio3", ['price'] = 5000, ['type'] = "motos" },
	["fcr"] = { ['name'] = "Fcr", ['price'] = 390000, ['type'] = "motos" },
	["fcr2"] = { ['name'] = "Fcr2", ['price'] = 390000, ['type'] = "motos" },
	["gargoyle"] = { ['name'] = "Gargoyle", ['price'] = 345000, ['type'] = "motos" },
	["hakuchou"] = { ['name'] = "Hakuchou", ['price'] = 380000, ['type'] = "motos" },
	["hakuchou2"] = { ['name'] = "Hakuchou2", ['price'] = 483000, ['type'] = "motos" },
	["hexer"] = { ['name'] = "Hexer", ['price'] = 250000, ['type'] = "motos" },
	["innovation"] = { ['name'] = "Innovation", ['price'] = 250000, ['type'] = "motos" },
	["lectro"] = { ['name'] = "Lectro", ['price'] = 380000, ['type'] = "motos" },
	["manchez"] = { ['name'] = "Manchez", ['price'] = 355000, ['type'] = "motos" },
	["nemesis"] = { ['name'] = "Nemesis", ['price'] = 345000, ['type'] = "motos" },
	["nightblade"] = { ['name'] = "Nightblade", ['price'] = 260000, ['type'] = "motos" },
	["pcj"] = { ['name'] = "Pcj", ['price'] = 17000, ['type'] = "motos" },
	["ruffian"] = { ['name'] = "Ruffian", ['price'] = 345000, ['type'] = "motos" },
	["sanchez"] = { ['name'] = "Sanchez", ['price'] = 185000, ['type'] = "motos" },
	["sanchez2"] = { ['name'] = "Sanchez2", ['price'] = 97000, ['type'] = "motos" },
	["sovereign"] = { ['name'] = "Sovereign", ['price'] = 285000, ['type'] = "motos" },
	["thrust"] = { ['name'] = "Thrust", ['price'] = 375000, ['type'] = "motos" },
	["vader"] = { ['name'] = "Vader", ['price'] = 140000, ['type'] = "motos" },
	["vindicator"] = { ['name'] = "Vindicator", ['price'] = 340000, ['type'] = "motos" },
	["vortex"] = { ['name'] = "Vortex", ['price'] = 98200, ['type'] = "motos" },
	["wolfsbane"] = { ['name'] = "Wolfsbane", ['price'] = 290000, ['type'] = "motos" },
	["zombiea"] = { ['name'] = "Zombiea", ['price'] = 290000, ['type'] = "motos" },
	["zombieb"] = { ['name'] = "Zombieb", ['price'] = 300000, ['type'] = "motos" },
	["shotaro"] = { ['name'] = "Shotaro", ['price'] = 500000, ['type'] = "motos" },
	["ratbike"] = { ['name'] = "Ratbike", ['price'] = 230000, ['type'] = "motos" },
	["blazer"] = { ['name'] = "Blazer", ['price'] = 230000, ['type'] = "motos" },
	["blazer4"] = { ['name'] = "Blazer4", ['price'] = 370000, ['type'] = "motos" },

	--TRABALHO

	["felon2"] = { ['name'] = "Felon2", ['price'] = 1000, ['type'] = "work" },
	["pbus"] = { ['name'] = "PBus", ['price'] = 1000, ['type'] = "work" },
	---------------------------------------------------------------------------------------
	-- Polícia -------------------------------------------------------------
	---------------------------------------------------------------------------------------
	["corollapc"] = { ['name'] = "Corolla", ['price'] = 1000, ['type'] = "work" },
	["dusterpc"] = { ['name'] = "Duster", ['price'] = 1000, ['type'] = "work" },
	["helipc"] = { ['name'] = "Helicóptero PC", ['price'] = 1000, ['type'] = "work" },

	["2015polstang"] = { ['name'] = "Mustang", ['price'] = 1000, ['type'] = "work" },

	["polmav"] = { ['name'] = "Heli BAIXADA", ['price'] = 1000, ['type'] = "work" },

	["helibope"] = { ['name'] = "Helicóptero BOPE", ['price'] = 1000, ['type'] = "work" },
	["hiluxsrvbope"] = { ['name'] = "Hilux", ['price'] = 1000, ['type'] = "work" },
	["s10bope"] = { ['name'] = "S10", ['price'] = 1000, ['type'] = "work" },
	["hiluxpf"] = { ['name'] = "Hilux Samu", ['price'] = 1000, ['type'] = "work" },	
	---------------------------------------------------------------------------------------
	-- Veículos -------------------------------------------------------------
	---------------------------------------------------------------------------------------
	["astra"] = { ['name'] = "Astra", ['price'] = 80000, ['type'] = "brasileiros" },
	["celta"] = { ['name'] = "Celta", ['price'] = 40000, ['type'] = "brasileiros" },
	["chevette"] = { ['name'] = "Chevette", ['price'] = 34000, ['type'] = "brasileiros" },
	["corsa98"] = { ['name'] = "Corsa 98", ['price'] = 27000, ['type'] = "brasileiros" },
	["cronos"] = { ['name'] = "Fiat Cronos", ['price'] = 57000, ['type'] = "br" },
	["escort"] = { ['name'] = "Escort", ['price'] = 25000, ['type'] = "br" },
	["fusca"] = { ['name'] = "Fusca", ['price'] = 22000, ['type'] = "br" },
	["hilux2016"] = { ['name'] = "Hilux 2016", ['price'] = 165000, ['type'] = "br" },
	["jetta"] = { ['name'] = "Jetta", ['price'] = 220000, ['type'] = "brasileiros" },
	["palio97"] = { ['name'] = "Palio 97", ['price'] = 40000, ['type'] = "br" },
	["passat"] = { ['name'] = "Passat", ['price'] = 250000, ['type'] = "brasileiros" },
	["s10"] = { ['name'] = "S10", ['price'] = 300000, ['type'] = "br" },
	["saveirog6"] = { ['name'] = "Saveiro G6", ['price'] = 180000, ['type'] = "br" },
	["tritonhpe"] = { ['name'] = "Triton", ['price'] = 310000, ['type'] = "br" },
	["uno"] = { ['name'] = "Uno", ['price'] = 70000, ['type'] = "br" },
	["versa"] = { ['name'] = "Nissan Versa", ['price'] = 120000, ['type'] = "br" },
	["bria"] = { ['name'] = "bria", ['price'] = 18000, ['type'] = "br" },
	["civic2016"] = { ['name'] = "Civic 2016", ['price'] = 80000, ['type'] = "br" },	
	["clio"] = { ['name'] = "Clio", ['price'] = 82000, ['type'] = "br" },
	["cruze"] = { ['name'] = "Cruze", ['price'] = 105000, ['type'] = "br" },
	["fiesta"] = { ['name'] = "New Fiesta", ['price'] = 100000, ['type'] = "br" },
	["ftoro"] = { ['name'] = "Fiat Toro", ['price'] = 120000, ['type'] = "br" },
	["omega"] = { ['name'] = "Omega", ['price'] = 70000, ['type'] = "br" },	
	["parati2007"] = { ['name'] = "Parati 2007", ['price'] = 63000, ['type'] = "br" },
	["peugeot207"] = { ['name'] = "Peugeot 207", ['price'] = 80000, ['type'] = "br" },
	["polo"] = { ['name'] = "Polo", ['price'] = 76000, ['type'] = "br" },
	["upzinho"] = { ['name'] = "Up", ['price'] = 35000, ['type'] = "carros" },
	["eletran17"] = { ['name'] = "Honda Eletran", ['price'] = 60000, ['type'] = "carros" },
	["19raptor"] = { ['name'] = "Ford Raptor", ['price'] = 150000, ['type'] = "carros" },
	["razerx3"] = { ['name'] = "Rally", ['price'] = 150000, ['type'] = "carros" },
	["streetr33"] = { ['name'] = "R33", ['price'] = 1500500, ['type'] = "carros" },
	["jza80"] = { ['name'] = "Supra Jza80", ['price'] = 2000000, ['type'] = "carros" },
	["supra19"] = { ['name'] = "Supra 2019", ['price'] = 2750000, ['type'] = "carros" }, 
	["pounder"] = { ['name'] = "Pounder", ['price'] = 1000000, ['type'] = "work" },
	["fk8"] = { ['name'] = "Civic PM", ['price'] = 1000, ['type'] = "work" },
	["passatt"] = { ['name'] = "Passatt PM", ['price'] = 1000, ['type'] = "work" },
	["coca"] = { ['name'] = "Porsche ROTA", ['price'] = 1000, ['type'] = "work" },
	["nm_esc"] = { ['name'] = "SUV PC", ['price'] = 1000, ['type'] = "work" },
	["ram2500"] = { ['name'] = "RAM2500", ['price'] = 1000, ['type'] = "work" },
	["bikelete"] = { ['name'] = "Bikelete", ['price'] = 1000, ['type'] = "motos" },
	["stockade3"] = { ['name'] = "Carro Forte", ['price'] = 1000, ['type'] = "work" },
	["cg160"] = { ['name'] = "CG Ifood", ['price'] = 1000, ['type'] = "work" },
	["fiattoro"] = { ['name'] = "Fiat Ttoro", ['price'] = 40000, ['type'] = "carros" },
	["fordka"] = { ['name'] = "Ford Ka", ['price'] = 35000, ['type'] = "carros" },
	["fusion"] = { ['name'] = "Fusion", ['price'] = 40000, ['type'] = "carros" },
	["golg7"] = { ['name'] = "Gol G7", ['price'] = 25000, ['type'] = "carros" },
	["jetta2017"] = { ['name'] = "Jetta 2017", ['price'] = 40000, ['type'] = "carros" },
	["l200civil"] = { ['name'] = "Mitsubishi L200", ['price'] = 100000, ['type'] = "carros" },
	["p207"] = { ['name'] = "Peugeot 2007", ['price'] = 10000, ['type'] = "carros" },
	["palio"] = { ['name'] = "Palio", ['price'] = 35000, ['type'] = "carros" },
	["punto"] = { ['name'] = "Fiat Punto", ['price'] = 50000, ['type'] = "carros" },
	["santafe"] = { ['name'] = "Honda Santafe", ['price'] = 100000, ['type'] = "carros" },
	["saveiro"] = { ['name'] = "Saveiro", ['price'] = 50000, ['type'] = "carros" },
	["sonata18"] = { ['name'] = "Honda Sonata", ['price'] = 60000, ['type'] = "carros" },
	["veloster"] = { ['name'] = "Veloster", ['price'] = 100000, ['type'] = "carros" },
	["voyage"] = { ['name'] = "Voyage", ['price'] = 60000, ['type'] = "carros" },
	["vwgolf"] = { ['name'] = "Golfzada 1.6 Peita", ['price'] = 25000, ['type'] = "carros" },
	["vwpolo"] = { ['name'] = "Palo", ['price'] = 35000, ['type'] = "carros" },
	["xj"] = { ['name'] = "XJ6", ['price'] = 100000, ['type'] = "motos" },
	-- Motos BR
	
	["cbrr"] = { ['name'] = "CBR 1000RR", ['price'] = 500000, ['type'] = "motos" },
	["150"] = { ['name'] = "Honda 150", ['price'] = 6000, ['type'] = "motos" },
	["z1000"] = { ['name'] = "Z1000", ['price'] = 200000, ['type'] = "motos" },
	["xt66"] = { ['name'] = "XT66", ['price'] = 7500, ['type'] = "motos" },
	["xj6"] = { ['name'] = "XJ", ['price'] = 120000, ['type'] = "motos" },
	["r1250"] = { ['name'] = "BMW R1250", ['price'] = 500000, ['type'] = "motos" },
	["hornet"] = { ['name'] = "Hornet", ['price'] = 50000, ['type'] = "motos" },
	["bros60"] = { ['name'] = "Bros 160", ['price'] = 7500, ['type'] = "motos" },
	["dm1200"] = { ['name'] = "Ducati 1200", ['price'] = 200000, ['type'] = "motos" },
	["biz25"] = { ['name'] = "Biz", ['price'] = 3000, ['type'] = "motos" },
	----------------------------------------------------------------------------------------------------
	["policiacharger2018"] = { ['name'] = "Dodge Charger 2018", ['price'] = 1000, ['type'] = "work" }, --
	["policiamustanggt"] = { ['name'] = "Mustang GT", ['price'] = 1000, ['type'] = "work" },
	["policiacapricesid"] = { ['name'] = "GM Caprice SID", ['price'] = 1000, ['type'] = "work" },
	["policiaschaftersid"] = { ['name'] = "GM Schafter SID", ['price'] = 1000, ['type'] = "work" },
	["policiasilverado"] = { ['name'] = "Chevrolet Silverado", ['price'] = 1000, ['type'] = "work" },
	["policiatahoe"] = { ['name'] = "Chevrolet Tahoe", ['price'] = 1000, ['type'] = "work" },
	["policiaexplorer"] = { ['name'] = "Ford Explorer", ['price'] = 1000, ['type'] = "work" },
	["policiataurus"] = { ['name'] = "Ford Taurus", ['price'] = 1000, ['type'] = "work" },
	["policiavictoria"] = { ['name'] = "Ford Victoria", ['price'] = 1000, ['type'] = "work" },
	["policiabmwr1200"] = { ['name'] = "BMW R1200", ['price'] = 1000, ['type'] = "work" },
	["policiaheli"] = { ['name'] = "Policia Helicóptero", ['price'] = 1000, ['type'] = "work" },
	["policeb"] = { ['name'] = "Africa Twin", ['price'] = 1000, ['type'] = "work" },
	["police"] = { ['name'] = "Police BAIXADA", ['price'] = 1000, ['type'] = "work" },
	["police2"] = { ['name'] = "Police BAIXADA - SPEED", ['price'] = 1000, ['type'] = "work" },
	["police3"] = { ['name'] = "Taticao BAIXADA", ['price'] = 1000, ['type'] = "work" },
	["pranger"] = { ['name'] = "Taticao BAIXADA - PATENTE", ['price'] = 1000, ['type'] = "work" },
	["riot"] = { ['name'] = "Taticao BAIXADA - Blindado", ['price'] = 1000, ['type'] = "work" },
	["sheriff"] = { ['name'] = "Civil BAIXADA", ['price'] = 1000, ['type'] = "work" },
	["ghispo2"] = { ['name'] = "Civil BAIXADA - Sheriff", ['price'] = 1000, ['type'] = "work" },
	["samumav"] = { ['name'] = "Heli Samu", ['price'] = 1000, ['type'] = "work" },
	["paramedicoambu"] = { ['name'] = "Ambulância", ['price'] = 1000, ['type'] = "work" },
	["paramedicocharger2014"] = { ['name'] = "Dodge Charger 2014", ['price'] = 1000, ['type'] = "work" },
	["paramedicoheli"] = { ['name'] = "Paramédico Helicóptero", ['price'] = 1000, ['type'] = "work" },
	["seasparrow"] = { ['name'] = "Paramédico Helicóptero Água", ['price'] = 1000, ['type'] = "work" },
	["coach"] = { ['name'] = "Coach", ['price'] = 1000, ['type'] = "work" },
	["bus"] = { ['name'] = "Ônibus", ['price'] = 1000, ['type'] = "work" },
	["flatbed"] = { ['name'] = "Reboque", ['price'] = 1000, ['type'] = "work" },
	["towtruck"] = { ['name'] = "Towtruck", ['price'] = 1000, ['type'] = "work" },
	["towtruck2"] = { ['name'] = "Towtruck2", ['price'] = 1000, ['type'] = "work" },
	["ratloader"] = { ['name'] = "Lenhador", ['price'] = 63000, ['type'] = "work" },
	["ratloader2"] = { ['name'] = "Ratloader2", ['price'] = 1000, ['type'] = "work" },
	["rubble"] = { ['name'] = "Caminhão", ['price'] = 1000, ['type'] = "work" },
	["taxi"] = { ['name'] = "Taxi", ['price'] = 1000, ['type'] = "work" },
	["boxville4"] = { ['name'] = "Caminhão", ['price'] = 1000, ['type'] = "work" },
	["trash2"] = { ['name'] = "Lixeiro", ['price'] = 1000, ['type'] = "work" },
	["trash"] = { ['name'] = "Lixeiro", ['price'] = 1000, ['type'] = "work" },
	["tiptruck"] = { ['name'] = "Tiptruck", ['price'] = 1000, ['type'] = "work" },
	["scorcher"] = { ['name'] = "Scorcher", ['price'] = 1000, ['type'] = "work" },
	["tribike"] = { ['name'] = "Tribike", ['price'] = 1000, ['type'] = "work" },
	["tribike2"] = { ['name'] = "Tribike2", ['price'] = 1000, ['type'] = "work" },
	["tribike3"] = { ['name'] = "Tribike3", ['price'] = 1000, ['type'] = "work" },
	["fixter"] = { ['name'] = "Fixter", ['price'] = 1000, ['type'] = "work" },
	["cruiser"] = { ['name'] = "Cruiser", ['price'] = 1000, ['type'] = "work" },
	["bmx"] = { ['name'] = "Bmx", ['price'] = 1000, ['type'] = "work" },
	["dinghy"] = { ['name'] = "Dinghy", ['price'] = 1000, ['type'] = "work" },
	["jetmax"] = { ['name'] = "Jetmax", ['price'] = 1000, ['type'] = "work" },
	["marquis"] = { ['name'] = "Marquis", ['price'] = 1000, ['type'] = "work" },
	["seashark3"] = { ['name'] = "Seashark3", ['price'] = 1000, ['type'] = "work" },
	["speeder"] = { ['name'] = "Speeder", ['price'] = 1000, ['type'] = "work" },
	["speeder2"] = { ['name'] = "Speeder2", ['price'] = 1000, ['type'] = "work" },
	["squalo"] = { ['name'] = "Squalo", ['price'] = 1000, ['type'] = "work" },
	["suntrap"] = { ['name'] = "Suntrap", ['price'] = 1000, ['type'] = "work" },
	["toro"] = { ['name'] = "Toro", ['price'] = 1000, ['type'] = "work" },
	["toro2"] = { ['name'] = "Toro2", ['price'] = 1000, ['type'] = "work" },
	["tropic"] = { ['name'] = "Tropic", ['price'] = 1000, ['type'] = "work" },
	["phantom"] = { ['name'] = "Phantom", ['price'] = 1000, ['type'] = "work" },
	["packer"] = { ['name'] = "Packer", ['price'] = 1000, ['type'] = "work" },
	["supervolito"] = { ['name'] = "Supervolito", ['price'] = 1000, ['type'] = "work" },
	["supervolito2"] = { ['name'] = "Supervolito2", ['price'] = 1000, ['type'] = "work" },
	["cuban800"] = { ['name'] = "Cuban800", ['price'] = 1000, ['type'] = "work" },
	["mammatus"] = { ['name'] = "Mammatus", ['price'] = 1000, ['type'] = "work" },
	["vestra"] = { ['name'] = "Vestra", ['price'] = 1000, ['type'] = "work" },
	["velum2"] = { ['name'] = "Velum2", ['price'] = 1000, ['type'] = "work" },
	["buzzard2"] = { ['name'] = "Buzzard2", ['price'] = 1000, ['type'] = "work" },
	["frogger"] = { ['name'] = "Frogger", ['price'] = 1000, ['type'] = "work" },
	["maverick"] = { ['name'] = "Maverick", ['price'] = 1000, ['type'] = "work" },
	["tanker2"] = { ['name'] = "Gas", ['price'] = 1000, ['type'] = "work" },
	["armytanker"] = { ['name'] = "Diesel", ['price'] = 1000, ['type'] = "work" },
	["tvtrailer"] = { ['name'] = "Show", ['price'] = 1000, ['type'] = "work" },
	["trailerlogs"] = { ['name'] = "Woods", ['price'] = 1000, ['type'] = "work" },
	["tr4"] = { ['name'] = "Cars", ['price'] = 1000, ['type'] = "work" },
	["speedo"] = { ['name'] = "Speedo", ['price'] = 200000, ['type'] = "work" },
	["primo2"] = { ['name'] = "Primo2", ['price'] = 40200, ['type'] = "work" },
	["faction2"] = { ['name'] = "Faction2", ['price'] = 200000, ['type'] = "work" },
	["chino2"] = { ['name'] = "Chino2", ['price'] = 72500, ['type'] = "work" },
	["tornado5"] = { ['name'] = "Tornado5", ['price'] = 200000, ['type'] = "work" },
	["daemon"] = { ['name'] = "Daemon", ['price'] = 62000, ['type'] = "work" },
	["sanctus"] = { ['name'] = "Sanctus", ['price'] = 200000, ['type'] = "work" },
	["gburrito"] = { ['name'] = "GBurrito", ['price'] = 200000, ['type'] = "work" },
	["slamvan2"] = { ['name'] = "Slamvan2", ['price'] = 200000, ['type'] = "work" },
	["stafford"] = { ['name'] = "Stafford", ['price'] = 95000, ['type'] = "work" },
	["cog55"] = { ['name'] = "Cog55", ['price'] = 200000, ['type'] = "work" },
	["superd"] = { ['name'] = "Superd", ['price'] = 200000, ['type'] = "work" },
	["btype"] = { ['name'] = "Btype", ['price'] = 200000, ['type'] = "work" },
	["tractor2"] = { ['name'] = "Tractor2", ['price'] = 1000, ['type'] = "work" },
	["rebel"] = { ['name'] = "Rebel", ['price'] = 1000, ['type'] = "work" },
	["flatbed3"] = { ['name'] = "flatbed3", ['price'] = 1000, ['type'] = "work" },
	["volatus"] = { ['name'] = "Volatus", ['price'] = 500000, ['type'] = "work" },
	["cargobob2"] = { ['name'] = "Cargo Bob", ['price'] = 500000, ['type'] = "work" },
	["cargobob"] = { ['name'] = "Cargo Bob", ['price'] = 500000, ['type'] = "work" },
	
	
	--IMPORTADOS

	["bmwm3f80"] = { ['name'] = "BMW M3 F80", ['price'] = 150000, ['type'] = "import" },
	["focusrs"] = { ['name'] = "Focus RS", ['price'] = 100000, ['type'] = "import" },
	["mercedesa45"] = { ['name'] = "Mercedes A45", ['price'] = 100000, ['type'] = "import" },
	["audirs7"] = { ['name'] = "Audi RS7", ['price'] = 100000, ['type'] = "import" },
	["hondafk8"] = { ['name'] = "Honda FK8", ['price'] = 100000, ['type'] = "import" },
	["porsche930"] = { ['name'] = "Porsche 930", ['price'] = 100000, ['type'] = "import" },
	["teslaprior"] = { ['name'] = "Tesla Prior", ['price'] = 100000, ['type'] = "import" },
	["type263"] = { ['name'] = "Kombi 63", ['price'] = 100000, ['type'] = "import" },
	["beetle74"] = { ['name'] = "Fusca 74", ['price'] = 100000, ['type'] = "import" },
	["fe86"] = { ['name'] = "Escorte", ['price'] = 100000, ['type'] = "import" },		

	--EXCLUSIVE 
	
	["i8"] = { ['name'] = "BMW i8", ['price'] = 500000, ['type'] = "exclusive" },
	["nissan370z"] = { ['name'] = "Nissan 370Z", ['price'] = 500000, ['type'] = "exclusive" },
	["raptor2017"] = { ['name'] = "Ford Raptor 2017", ['price'] = 500000, ['type'] = "exclusive" },	
	["supratuning"] = { ['name'] = "Supra mk4 v1", ['price'] = 500000, ['type'] = "exclusive" },
	["trdsupra"] = { ['name'] = "Supra mk4 Super", ['price'] = 500000, ['type'] = "exclusive" },
	["r33vspec"] = { ['name'] = "R33 V-Spec", ['price'] = 500000, ['type'] = "exclusive" },
	["evoix"] = { ['name'] = "Lancer Evolutionx 9", ['price'] = 500000, ['type'] = "exclusive" },
	["lbwk35"] = { ['name'] = "R35 Libert Walk", ['price'] = 500000, ['type'] = "exclusive" },
	["nissanskyliner34"] = { ['name'] = "Nissan Skyline R34", ['price'] = 500000, ['type'] = "exclusive" },
	["bc"] = { ['name'] = "Pagani Huayra", ['price'] = 500000, ['type'] = "exclusive" },
	["488gtb"] = { ['name'] = "Ferrari 488 GTB", ['price'] = 500000, ['type'] = "exclusive" },
	["fxxkevo"] = { ['name'] = "Ferrari FXXK Evo", ['price'] = 500000, ['type'] = "exclusive" },
	["m2"] = { ['name'] = "BMW M2", ['price'] = 500000, ['type'] = "exclusive" },
	["p1"] = { ['name'] = "Mclaren P1", ['price'] = 500000, ['type'] = "exclusive" },
	["aperta"] = { ['name'] = "La Ferrari", ['price'] = 500000, ['type'] = "exclusive" },
	["bettle"] = { ['name'] = "New Bettle", ['price'] = 500000, ['type'] = "exclusive" },
	["senna"] = { ['name'] = "Mclaren Senna", ['price'] = 500000, ['type'] = "exclusive" },
	["rmodx6"] = { ['name'] = "BMW X6", ['price'] = 500000, ['type'] = "exclusive" },
	["bnteam"] = { ['name'] = "Bentley", ['price'] = 500000, ['type'] = "exclusive" },
	["rmodlp770"] = { ['name'] = "Lamborghini Centenario", ['price'] = 500000, ['type'] = "exclusive" },
	["s15"] = { ['name'] = "Nissan Silvia S15", ['price'] = 500000, ['type'] = "exclusive" },
	["amggtr"] = { ['name'] = "Mercedes AMG", ['price'] = 500000, ['type'] = "exclusive" },
	["slsamg"] = { ['name'] = "Mercedes SLS", ['price'] = 500000, ['type'] = "exclusive" },
	["lamtmc"] = { ['name'] = "Lamborghini Terzo", ['price'] = 500000, ['type'] = "exclusive" },
	["vantage"] = { ['name'] = "Aston Martin Vantage", ['price'] = 500000, ['type'] = "exclusive" },
	["amarok"] = { ['name'] = "VW Amarok", ['price'] = 300000, ['type'] = "carros" },
	["g65amg"] = { ['name'] = "Mercedes G65", ['price'] = 500000, ['type'] = "exclusive" },
	["palameila"] = { ['name'] = "Porsche Panamera", ['price'] = 500000, ['type'] = "exclusive" },
	["rsvr16"] = { ['name'] = "Ranger Rover", ['price'] = 500000, ['type'] = "exclusive" },
	["veneno"] = { ['name'] = "Lamborghini Veneno", ['price'] = 500000, ['type'] = "exclusive" },
	["eleanor"] = { ['name'] = "Mustang Eleanor", ['price'] = 500000, ['type'] = "exclusive" },
	["rmodamgc63"] = { ['name'] = "Mercedes AMG C63", ['price'] = 500000, ['type'] = "exclusive" },
	["19ramdonk"] = { ['name'] = "Dodge Ram Donk", ['price'] = 500000, ['type'] = "exclusive" },
	["silv86"] = { ['name'] = "Silverado Donk", ['price'] = 500000, ['type'] = "exclusive" },
	["ninjah2"] = { ['name'] = "Ninja H2", ['price'] = 500000, ['type'] = "exclusive" },
	["70camarofn"] = { ['name'] = "camaro Z28 1970", ['price'] = 500000, ['type'] = "exclusive" },
	["agerars"] = { ['name'] = "Koenigsegg Agera RS", ['price'] = 500000, ['type'] = "exclusive" },
	["fc15"] = { ['name'] = "Ferrari California", ['price'] = 500000, ['type'] = "exclusive" },
	["msohs"] = { ['name'] = "Mclaren 688 HS", ['price'] = 500000, ['type'] = "exclusive" },
	["gt17"] = { ['name'] = "Ford GT 17", ['price'] = 500000, ['type'] = "exclusive" },
	["19ftype"] = { ['name'] = "Jaguar F-Type", ['price'] = 500000, ['type'] = "exclusive" },
	["bbentayga"] = { ['name'] = "Bentley Bentayga", ['price'] = 500000, ['type'] = "exclusive" },
	["nissantitan17"] = { ['name'] = "Nissan Titan 2017", ['price'] = 350000, ['type'] = "carros" },
	["911r"] = { ['name'] = "Porsche 911R", ['price'] = 500000, ['type'] = "exclusive" },
	["trr"] = { ['name'] = "KTM TRR", ['price'] = 500000, ['type'] = "exclusive" },
	["bmws"] = { ['name'] = "BMW S1000", ['price'] = 500000, ['type'] = "exclusive" },
	["cb500x"] = { ['name'] = "Honda CB500", ['price'] = 500000, ['type'] = "exclusive" },
	["hcbr17"] = { ['name'] = "Honda CBR17", ['price'] = 500000, ['type'] = "exclusive" },
	["defiant"] = { ['name'] = "AMC Javelin 72", ['price'] = 500000, ['type'] = "exclusive" },
	["f12tdf"] = { ['name'] = "Ferrari F12 TDF", ['price'] = 500000, ['type'] = "exclusive" },
	["71gtx"] = { ['name'] = "Plymouth 71 GTX", ['price'] = 500000, ['type'] = "exclusive" },
	["porsche992"] = { ['name'] = "Porsche 992", ['price'] = 500000, ['type'] = "exclusive" },
	["18macan"] = { ['name'] = "Porsche Macan", ['price'] = 500000, ['type'] = "exclusive" },
	["m6e63"] = { ['name'] = "BMW M6 E63", ['price'] = 500000, ['type'] = "exclusive" },
	["africat"] = { ['name'] = "Honda CRF 1000", ['price'] = 500000, ['type'] = "exclusive" },
	["regera"] = { ['name'] = "Koenigsegg Regera", ['price'] = 500000, ['type'] = "exclusive" },
	["180sx"] = { ['name'] = "Nissan 180SX", ['price'] = 500000, ['type'] = "exclusive" },
	["filthynsx"] = { ['name'] = "Honda NSX", ['price'] = 500000, ['type'] = "exclusive" },
	["2018zl1"] = { ['name'] = "Camaro ZL1", ['price'] = 500000, ['type'] = "exclusive" },
	["eclipse"] = { ['name'] = "Mitsubishi Eclipse", ['price'] = 500000, ['type'] = "exclusive" },
	["lp700r"] = { ['name'] = "Lamborghini LP700R", ['price'] = 500000, ['type'] = "exclusive" },
	["db11"] = { ['name'] = "Aston Martin DB11", ['price'] = 500000, ['type'] = "exclusive" },
	["SVR14"] = { ['name'] = "Ranger Rover", ['price'] = 500000, ['type'] = "exclusive" },
	["evoque"] = { ['name'] = "Ranger Rover Evoque", ['price'] = 500000, ['type'] = "exclusive" },
	["Bimota"] = { ['name'] = "Ducati Bimota", ['price'] = 500000, ['type'] = "exclusive" },
	["r8ppi"] = { ['name'] = "Audi R8 PPI Razor", ['price'] = 500000, ['type'] = "exclusive" },
	["20r1"] = { ['name'] = "Yamaha YZF R1", ['price'] = 500000, ['type'] = "exclusive" },
	["mt03"] = { ['name'] = "Yamaha MT 03", ['price'] = 500000, ['type'] = "exclusive" },
	["yzfr125"] = { ['name'] = "Yamaha YZF R125", ['price'] = 500000, ['type'] = "exclusive" },
	["pistas"] = { ['name'] = "Ferrari Pista", ['price'] = 500000, ['type'] = "exclusive" },
	["bobbes2"] = { ['name'] = "Harley D. Bobber S", ['price'] = 500000, ['type'] = "exclusive" },
	["bobber"] = { ['name'] = "Harley D. Bobber ", ['price'] = 500000, ['type'] = "exclusive" },
	["911tbs"] = { ['name'] = "Porsche 911S", ['price'] = 500000, ['type'] = "exclusive" },		
	["rc"] = { ['name'] = "KTM RC", ['price'] = 500000, ['type'] = "exclusive" },		
	["zx10r"] = { ['name'] = "Kawasaki ZX10R", ['price'] = 500000, ['type'] = "exclusive" },		
	["fox600lt"] = { ['name'] = "McLaren 600LT", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxbent1"] = { ['name'] = "Bentley Liter 1931", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxevo"] = { ['name'] = "Lamborghini EVO", ['price'] = 500000, ['type'] = "exclusive" },		
	["jeepg"] = { ['name'] = "Jeep Gladiator", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxharley1"] = { ['name'] = "Harley-Davidson Softail F.B.", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxharley2"] = { ['name'] = "2016 Harley-Davidson Road Glide", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxleggera"] = { ['name'] = "Aston Martin Leggera", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxrossa"] = { ['name'] = "Ferrari Rossa", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxshelby"] = { ['name'] = "Ford Shelby GT500", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxsian"] = { ['name'] = "Lamborghini Sian", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxsterrato"] = { ['name'] = "Lamborghini Sterrato", ['price'] = 500000, ['type'] = "exclusive" },		
	["foxsupra"] = { ['name'] = "Toyota Supra", ['price'] = 500000, ['type'] = "exclusive" },	
	["evolution"] = { ['name'] = "Lancer Libert Walk", ['price'] = 500000, ['type'] = "exclusive" },		
	["m6x6"] = { ['name'] = "Mercedes Benz 6x6", ['price'] = 500000, ['type'] = "exclusive" },		
	["m6gt3"] = { ['name'] = "BMW M6 GT3", ['price'] = 500000, ['type'] = "exclusive" },		
	["w900"] = { ['name'] = "Kenworth W900", ['price'] = 500000, ['type'] = "exclusive" },
	["terzo"] = { ['name'] = "Lamborghini Terzo", ['price'] = 500000, ['type'] = "exclusive" },
	["monza"] = { ['name'] = "Ferrari Monza", ['price'] = 10000, ['type'] = "carros" },
	["bmwm3e36"] = { ['name'] = "bmwm3e36", ['price'] = 500000, ['type'] = "exclusive" },
	["a45amg"] = { ['name'] = "a45amg", ['price'] = 500000, ['type'] = "exclusive" },
	["bnr34"] = { ['name'] = "Skyline R34", ['price'] = 500000, ['type'] = "exclusive" },
	["tuatara"] = { ['name'] = "Tuatara", ['price'] = 500000, ['type'] = "exclusive" },
	["tropic2"] = { ['name'] = "IATE DE LUXO", ['price'] = 500000, ['type'] = "exclusive" },
	["c8"] = { ['name'] = "c8", ['price'] = 500000, ['type'] = "exclusive" },
	["xxxxx"] = { ['name'] = "xxxxx", ['price'] = 500000, ['type'] = "exclusive" },
	["18velar"] = { ['name'] = "18velar", ['price'] = 500000, ['type'] = "exclusive" },
	["bolide"] = { ['name'] = "bolide", ['price'] = 500000, ['type'] = "exclusive" },
	["divo"] = { ['name'] = "divo", ['price'] = 500000, ['type'] = "exclusive" },
	["gtr50"] = { ['name'] = "gtr50", ['price'] = 500000, ['type'] = "exclusive" },
	["mache"] = { ['name'] = "mache", ['price'] = 500000, ['type'] = "exclusive" },
	["pgt3"] = { ['name'] = "pgt3", ['price'] = 500000, ['type'] = "exclusive" },
	["r8v10"] = { ['name'] = "r8v10", ['price'] = 500000, ['type'] = "exclusive" },
	["rmodjeep"] = { ['name'] = "rmodjeep", ['price'] = 500000, ['type'] = "exclusive" },
	["srt8"] = { ['name'] = "srt8", ['price'] = 500000, ['type'] = "exclusive" },
	["variszupra"] = { ['name'] = "variszupra", ['price'] = 500000, ['type'] = "exclusive" },
	["techart17"] = { ['name'] = "techart17", ['price'] = 500000, ['type'] = "exclusive" },
	["m1000rr "] = { ['name'] = "m1000rr", ['price'] = 500000, ['type'] = "exclusive" },
	["tigerrocam "] = { ['name'] = "tigerrocam", ['price'] = 1000, ['type'] = "work" },

	["m5f90"] = { ['name'] = "BMW M5", ['price'] = 500000, ['type'] = "exclusive" },
	["trailers2"] = { ['name'] = "Carreta Baú", ['price'] = 1800000, ['type'] = "carros" },
	["hauler"] = { ['name'] = "Hauler", ['price'] = 100000, ['type'] = "carros" },
	["phantom3"] = { ['name'] = "Phantom 3", ['price'] = 200000, ['type'] = "carros" },
	["entity2"] = { ['name'] = "Entity 2", ['price'] = 200000, ['type'] = "carros" },
	["visione"] = { ['name'] = "Visione", ['price'] = 200000, ['type'] = "carros" },
	["tyrus"] = { ['name'] = "Tyrus", ['price'] = 200000, ['type'] = "carros" },
	["autarch"] = { ['name'] = "Autarch", ['price'] = 200000, ['type'] = "carros" },
	["osiris"] = { ['name'] = "osiris", ['price'] = 200000, ['type'] = "carros" },

	["italirsx"] = { ['name'] = "italirsx", ['price'] = 200000, ['type'] = "carros" },
	["schlagen"] = { ['name'] = "schlagen", ['price'] = 200000, ['type'] = "carros" },
	["neon"] = { ['name'] = "neon", ['price'] = 200000, ['type'] = "carros" },
	["silveradope"] = { ['name'] = "Police BAIXADA", ['price'] = 50000, ['type'] = "carros" },
	["fbi2"] = { ['name'] = "Police BAIXADA FBI2", ['price'] = 50000, ['type'] = "carros" },
	["kuruma2"] = { ['name'] = "Kuruma Blindado", ['price'] = 50000, ['type'] = "carros" },
	["amarokpolicia"] = { ['name'] = "Amarok Police", ['price'] = 50000, ['type'] = "work" },
	["mercedespolicia"] = { ['name'] = "Mercedes Police", ['price'] = 50000, ['type'] = "work" },
	["pd_i8"] = { ['name'] = "I8 Police", ['price'] = 50000, ['type'] = "work" },
	["pdfocus"] = { ['name'] = "Focus Police", ['price'] = 50000, ['type'] = "work" },
	["tigerpolicia"] = { ['name'] = "Moto Police", ['price'] = 50000, ['type'] = "work" },
	["krieger"] = { ['name'] = "Krieger", ['price'] = 700000, ['type'] = "carros" },
	["zorrusso"] = { ['name'] = "Zorruso", ['price'] = 700000, ['type'] = "carros" },
	["nh2r"] = { ['name'] = "Ninja", ['price'] = 700000, ['type'] = "carros" },
	["sultanrs"] = { ['name'] = "Sultans RS", ['price'] = 400000, ['type'] = "carros" },
	["HellcatRed"] = { ['name'] = "Sultans RS", ['price'] = 400000, ['type'] = "carros" },
	["mercedesgle"] = { ['name'] = "Mercedes GLE", ['price'] = 50000, ['type'] = "work" },
	["mercedesgt"] = { ['name'] = "Mercedes GT", ['price'] = 50000, ['type'] = "work" },
	["mbsprinter"] = { ['name'] = "Sprinter", ['price'] = 50000, ['type'] = "work" },
	["mercxclass"] = { ['name'] = "X Class", ['price'] = 50000, ['type'] = "work" },
	["a45policia"] = { ['name'] = "Mercedes A45", ['price'] = 50000, ['type'] = "work" },
	["beetleRWB"] = { ['name'] = "Beetle RWB", ['price'] = 30000, ['type'] = "carros" },
	["hiluxsw4"] = { ['name'] = "Hilux SW4 PM", ['price'] = 50000, ['type'] = "work" },
	["spacerp"] = { ['name'] = "Fox PM", ['price'] = 50000, ['type'] = "work" },
	["spinrp"] = { ['name'] = "Spin PM", ['price'] = 50000, ['type'] = "work" },
	["sw4desc"] = { ['name'] = "SW4 Descaracterizada", ['price'] = 50000, ['type'] = "work" },
	["sw4ft"] = { ['name'] = "SW4 PM", ['price'] = 50000, ['type'] = "work" },
	["sw4pc"] = { ['name'] = "SW4 PC", ['price'] = 50000, ['type'] = "work" },
	["sw4rota"] = { ['name'] = "SW4 ROTA", ['price'] = 50000, ['type'] = "work" },
	["tigerpm"] = { ['name'] = "Tiger PM", ['price'] = 50000, ['type'] = "work" },
	["trail19rt"] = { ['name'] = "Trail PM", ['price'] = 50000, ['type'] = "work" },
	["trailblazermd19"] = { ['name'] = "Blazer PM", ['price'] = 50000, ['type'] = "work" },
	["xrer"] = { ['name'] = "XRE 300 PM", ['price'] = 50000, ['type'] = "work" },
	["cullinan"] = { ['name'] = "Cullinan", ['price'] = 100000, ['type'] = "carros" },
	["mvisiongt"] = { ['name'] = "Mvisiongt", ['price'] = 100000, ['type'] = "carros" },
	["urus"] = { ['name'] = "Urus", ['price'] = 100000, ['type'] = "carros" },
	["bme6tun"] = { ['name'] = "BMW", ['price'] = 100000, ['type'] = "carros" },
	["mustangmach1"] = { ['name'] = "Mustang Mach", ['price'] = 50000, ['type'] = "carros" },
	["cyrus"] = { ['name'] = "Cyrus", ['price'] = 50000, ['type'] = "carros" },

	--POLICIA
	["l200prf"] = { ['name'] = "L200 PRF", ['price'] = 1000, ['type'] = "work" },
	["africaprf"] = { ['name'] = "Africa PRF", ['price'] = 1000, ['type'] = "work" },
	["trailprf"] = { ['name'] = "Trail PRF", ['price'] = 1000, ['type'] = "work" },
	["rota4"] = { ['name'] = "Rota4", ['price'] = 1000, ['type'] = "work" },
	["sw4revrota1"] = { ['name'] = "SW4 Rota1", ['price'] = 1000, ['type'] = "work" },
	["trailrota2"] = { ['name'] = "Trail Rota2", ['price'] = 1000, ['type'] = "work" },
	["spinrp4"] = { ['name'] = "Spinrp4", ['price'] = 1000, ['type'] = "work" },
	["trail19goe"] = { ['name'] = "Trail19 GOE", ['price'] = 1000, ['type'] = "work" },
	["youga2"] = { ['name'] = "Corolla PRF", ['price'] = 1000, ['type'] = "work" },
	["paliopmrp1"] = { ['name'] = "paliopmrp1", ['price'] = 1000, ['type'] = "work" },
	["trailpm1"] = { ['name'] = "trailpm1", ['price'] = 1000, ['type'] = "work" },
	["spinpmesp"] = { ['name'] = "spinpmesp", ['price'] = 1000, ['type'] = "work" },
	["golpmesp"] = { ['name'] = "golpmesp", ['price'] = 1000, ['type'] = "work" },
	["corprf"] = { ['name'] = "Corolla PRF", ['price'] = 1000, ['type'] = "work" },
	["cruzeprf2"] = { ['name'] = "Cruze PRF", ['price'] = 1000, ['type'] = "work" },
	["motosamu"] = { ['name'] = "Moto Samu", ['price'] = 1000, ['type'] = "work" },
	["xre2019"] = { ['name'] = "XRE 2019", ['price'] = 1000, ['type'] = "work" },
	["trail17pm"] = { ['name'] = "Trail PM 2017", ['price'] = 1000, ['type'] = "work" },
	["trail20pm"] = { ['name'] = "Trail PM 2020", ['price'] = 1000, ['type'] = "work" },
	["trail21pm"] = { ['name'] = "Trail PM 2021", ['price'] = 1000, ['type'] = "work" },
	["spinaegis"] = { ['name'] = "SPIN PMESP", ['price'] = 1000, ['type'] = "work" },
	["spineng"] = { ['name'] = "SPIN G PMESP", ['price'] = 1000, ['type'] = "work" },
	["spinlegion"] = { ['name'] = "SPIN LEGION", ['price'] = 1000, ['type'] = "work" },
	["xre19rpm"] = { ['name'] = "XRE PM 2019", ['price'] = 1000, ['type'] = "work" },
	["xt2017pm"] = { ['name'] = "XT PM 2017", ['price'] = 1000, ['type'] = "work" },
	["trail21pc"] = { ['name'] = "Trail PC 2021", ['price'] = 1000, ['type'] = "work" },
	["traildope3"] = { ['name'] = "Trail DOPE", ['price'] = 1000, ['type'] = "work" },
	["trailcivileie"] = { ['name'] = "Trail EIE", ['price'] = 1000, ['type'] = "work" },
	["as350pc"] = { ['name'] = "AGUIA PC", ['price'] = 1000, ['type'] = "work" },
	["as350"] = { ['name'] = "AGUIA PM", ['price'] = 1000, ['type'] = "work" },
	["350z"] = { ['name'] = "350z", ['price'] = 1000, ['type'] = "carros" },
	["acuransx"] = { ['name'] = "acuransx", ['price'] = 1000, ['type'] = "carros" },
	["ambulance"] = { ['name'] = "ambulance", ['price'] = 1000, ['type'] = "carros" },
	["astonmartindbs"] = { ['name'] = "astonmartindbs", ['price'] = 1000, ['type'] = "carros" },
	["audia3"] = { ['name'] = "350z", ['price'] = 1000, ['type'] = "carros" },
	["audia4"] = { ['name'] = "audia4", ['price'] = 1000, ['type'] = "carros" },
	["audiq8"] = { ['name'] = "audiq8", ['price'] = 1000, ['type'] = "carros" },
	["audir8"] = { ['name'] = "audir8", ['price'] = 1000, ['type'] = "carros" },
	["audirs5"] = { ['name'] = "audirs5", ['price'] = 1000, ['type'] = "carros" },
	["audirs6"] = { ['name'] = "audirs6", ['price'] = 1000, ['type'] = "carros" },
	["audirs6avant"] = { ['name'] = "audirs6avant", ['price'] = 1000, ['type'] = "carros" },
	["audirs62"] = { ['name'] = "audirs62", ['price'] = 1000, ['type'] = "carros" },
	["bloodline"] = { ['name'] = "bloodline", ['price'] = 1000, ['type'] = "carros" },
	["bmwi8"] = { ['name'] = "bmwi8", ['price'] = 1000, ['type'] = "carros" },
	["bmwm1wb"] = { ['name'] = "bmwm1wb", ['price'] = 1000, ['type'] = "carros" },
	["bmwm4gts"] = { ['name'] = "bmwm4gts", ['price'] = 1000, ['type'] = "carros" },
	["bmwm5e34"] = { ['name'] = "bmwm5e34", ['price'] = 1000, ['type'] = "carros" },
	["camaro"] = { ['name'] = "camaro", ['price'] = 1000, ['type'] = "carros" },
	["civictyper"] = { ['name'] = "civictyper", ['price'] = 1000, ['type'] = "carros" },
	["dodgecharger1970"] = { ['name'] = "dodgecharger1970", ['price'] = 1000, ['type'] = "carros" },
	["dodgechargerrt69"] = { ['name'] = "dodgechargerrt69", ['price'] = 1000, ['type'] = "carros" },
	["dodgechargersrt"] = { ['name'] = "dodgechargersrt", ['price'] = 1000, ['type'] = "carros" },
	["dodgeramtrx"] = { ['name'] = "dodgeramtrx", ['price'] = 1000, ['type'] = "carros" },
	["ducati1200"] = { ['name'] = "ducati1200", ['price'] = 1000, ['type'] = "carros" },
	["escalade2021"] = { ['name'] = "escalade2021", ['price'] = 1000, ['type'] = "carros" },
	["escaladegt900"] = { ['name'] = "escaladegt900", ['price'] = 1000, ['type'] = "carros" },
	["f8t"] = { ['name'] = "f8t", ['price'] = 1000, ['type'] = "carros" },
	["ferrari812"] = { ['name'] = "ferrari812", ['price'] = 1000, ['type'] = "carros" },
	["ferrarif12"] = { ['name'] = "ferrarif12", ['price'] = 1000, ['type'] = "carros" },
	["ferrarif40"] = { ['name'] = "ferrarif40", ['price'] = 1000, ['type'] = "carros" },
	["ferrariitalia"] = { ['name'] = "ferrariitalia", ['price'] = 1000, ['type'] = "carros" },
	["fordbronco"] = { ['name'] = "fordbronco", ['price'] = 1000, ['type'] = "carros" },
	["fordmustang"] = { ['name'] = "fordmustang", ['price'] = 1000, ['type'] = "carros" },
	["fordraptor"] = { ['name'] = "fordraptor", ['price'] = 1000, ['type'] = "carros" },
	["golf75r"] = { ['name'] = "golf75r", ['price'] = 1000, ['type'] = "carros" },
	["golfgti"] = { ['name'] = "golfgti", ['price'] = 1000, ['type'] = "carros" },
	["golfmk7"] = { ['name'] = "golfmk7", ['price'] = 1000, ['type'] = "carros" },
	["jeepcherokee"] = { ['name'] = "jeepcherokee", ['price'] = 1000, ['type'] = "carros" },
	["lamborghinihuracan"] = { ['name'] = "lamborghinihuracan", ['price'] = 1000, ['type'] = "carros" },
	["lamborghinihuracanlw"] = { ['name'] = "lamborghinihuracanlw", ['price'] = 1000, ['type'] = "carros" },
	["lancerevolution9"] = { ['name'] = "lancerevolution9", ['price'] = 1000, ['type'] = "carros" },
	["lancerevolutionx"] = { ['name'] = "lancerevolutionx", ['price'] = 1000, ['type'] = "carros" },
	["manchez2"] = { ['name'] = "manchez2", ['price'] = 1000, ['type'] = "carros" },
	["maverick2"] = { ['name'] = "maverick2", ['price'] = 1000, ['type'] = "carros" },
	["mazdarx7"] = { ['name'] = "mazdarx7", ['price'] = 1000, ['type'] = "carros" },
	["mazdarx72"] = { ['name'] = "mazdarx72", ['price'] = 1000, ['type'] = "carros" },
	["mclarenp1"] = { ['name'] = "3mclarenp150z", ['price'] = 1000, ['type'] = "carros" },
	["mclarensenna"] = { ['name'] = "mclarensenna", ['price'] = 1000, ['type'] = "carros" },
	["mercedesamg63"] = { ['name'] = "mercedesamg63", ['price'] = 1000, ['type'] = "carros" },
	["mercedesgt63"] = { ['name'] = "mercedesgt63", ['price'] = 1000, ['type'] = "carros" },
	["mustangfast"] = { ['name'] = "mustangfast", ['price'] = 1000, ['type'] = "carros" },
	["nissangtr"] = { ['name'] = "nissangtr", ['price'] = 1000, ['type'] = "carros" },
	["nissangtr2"] = { ['name'] = "nissangtr2", ['price'] = 1000, ['type'] = "carros" },
	["nissangtr3"] = { ['name'] = "nissangtr3", ['price'] = 1000, ['type'] = "carros" },
	["nissangtr50"] = { ['name'] = "nissangtr50", ['price'] = 1000, ['type'] = "carros" },
	["nissangtrnismo"] = { ['name'] = "nissangtrnismo", ['price'] = 1000, ['type'] = "carros" },
	["nspeedo"] = { ['name'] = "nspeedo", ['price'] = 1000, ['type'] = "carros" },
	["panameramansory"] = { ['name'] = "panameramansory", ['price'] = 1000, ['type'] = "carros" },
	["polmesa"] = { ['name'] = "polmesa", ['price'] = 1000, ['type'] = "carros" },
	["porsche718"] = { ['name'] = "porsche718", ['price'] = 1000, ['type'] = "carros" },
	["porsche911"] = { ['name'] = "porsche911", ['price'] = 1000, ['type'] = "carros" },
	["r1"] = { ['name'] = "r1", ['price'] = 1000, ['type'] = "carros" },
	["r6"] = { ['name'] = "r6", ['price'] = 1000, ['type'] = "carros" },
	["rs52018"] = { ['name'] = "rs52018", ['price'] = 1000, ['type'] = "carros" },
	["s1000rr"] = { ['name'] = "s1000rr", ['price'] = 1000, ['type'] = "carros" },
	["sanchez3"] = { ['name'] = "sanchez3", ['price'] = 1000, ['type'] = "carros" },
	["shelbygt500"] = { ['name'] = "shelbygt500", ['price'] = 1000, ['type'] = "carros" },
	["silverado1500"] = { ['name'] = "silverado1500", ['price'] = 1000, ['type'] = "carros" },
	["skyliner34"] = { ['name'] = "skyliner34", ['price'] = 1000, ['type'] = "carros" },
	["skyliner342"] = { ['name'] = "skyliner342", ['price'] = 1000, ['type'] = "carros" },
	["stockade"] = { ['name'] = "stockade", ['price'] = 1000, ['type'] = "carros" },
	["subarubrz"] = { ['name'] = "subarubrz", ['price'] = 1000, ['type'] = "carros" },
	["subaruimpreza"] = { ['name'] = "subaruimpreza", ['price'] = 1000, ['type'] = "carros" },
	["tahoe"] = { ['name'] = "3tahoe50z", ['price'] = 1000, ['type'] = "carros" },
	["toyotasupra"] = { ['name'] = "toyotasupra", ['price'] = 1000, ['type'] = "carros" },
	["toyotasupra2"] = { ['name'] = "toyotasupra2", ['price'] = 1000, ['type'] = "carros" },
	["urbandevil"] = { ['name'] = "urbandevil", ['price'] = 1000, ['type'] = "carros" },
	["wheelchair"] = { ['name'] = "wheelchair", ['price'] = 1000, ['type'] = "carros" },
	["winky2"] = { ['name'] = "winky2", ['price'] = 1000, ['type'] = "carros" },
	["VRa3"] = { ['name'] = "VRa3", ['price'] = 1000, ['type'] = "carros" },
	["VRa4"] = { ['name'] = "VRa4", ['price'] = 1000, ['type'] = "carros" },
	["VRdm1200"] = { ['name'] = "VRdm1200", ['price'] = 1000, ['type'] = "carros" },
	["VRq8"] = { ['name'] = "VRq8", ['price'] = 1000, ['type'] = "carros" },
	["VRraptor"] = { ['name'] = "VRraptor", ['price'] = 1000, ['type'] = "carros" },
	["VRrs5"] = { ['name'] = "VRrs5", ['price'] = 1000, ['type'] = "carros" },
	["VRrs6"] = { ['name'] = "VRrs6", ['price'] = 1000, ['type'] = "carros" },
	["VRrs6av"] = { ['name'] = "VRrs6av", ['price'] = 1000, ['type'] = "carros" },
	["VRtahoe"] = { ['name'] = "VRtahoe", ['price'] = 1000, ['type'] = "carros" },
}

return vehs