-----------------------------------------------------------------------------------------------------------------------------------------
-- IPLLOADER
-----------------------------------------------------------------------------------------------------------------------------------------
CreateThread(function()
	LoadMpDlcMaps()
	EnableMpDlcMaps(1)
	RequestIpl("gabz_pillbox_milo_")
	RequestIpl("coronertrash")
	RequestIpl("Coroner_Int_On")
	RequestIpl("chop_props")
	RemoveIpl("hei_bi_hw1_13_door")
	RequestIpl("v_rockclub")
	RemoveIpl("rc12b_fixed")
	RemoveIpl("rc12b_destroyed")
	RequestIpl("rc12b_default")
	RemoveIpl("rc12b_hospitalinterior_lod")
	RemoveIpl("rc12b_hospitalinterior")
	RemoveIpl("v_carshowroom")
	RemoveIpl("shutter_open")
	RemoveIpl("shutter_closed")
	RemoveIpl("DES_StiltHouse_imapend")
	RequestIpl("DES_stilthouse_rebuild")
	RemoveIpl("shr_int")
	RemoveIpl("csr_inMission")
	RequestIpl("v_carshowroom")
	RequestIpl("shr_int")
	RequestIpl("shutter_closed")
	RequestIpl("FINBANK")
	RemoveIpl("facelobbyfake")
	RequestIpl("facelobby")
	RemoveIpl("CS1_02_cf_offmission")
	RequestIpl("CS1_02_cf_onmission1")
	RequestIpl("CS1_02_cf_onmission2")
	RequestIpl("CS1_02_cf_onmission3")
	RequestIpl("CS1_02_cf_onmission4")
	RequestIpl("des_farmhouse")
	RequestIpl("des_farmhs_endimap")
	RequestIpl("des_farmhs_end_occl")
	RequestIpl("des_farmhs_startimap")
	RequestIpl("des_farmhs_start_occl")
	RequestIpl("farm")
	RequestIpl("farm_props")
	RequestIpl("farm_int")
	RequestIpl("farmint")
	RemoveIpl("farm_burnt")
	RemoveIpl("farm_burnt_props")
	RemoveIpl("des_farmhs_endimap")
	RemoveIpl("des_farmhs_end_occl")
	RequestIpl("FIBlobby")
	RemoveIpl("FIBlobbyfake")
	RequestIpl("FBI_colPLUG")
	RequestIpl("FBI_repair")
	RemoveIpl("id2_14_during_door")
	RemoveIpl("id2_14_during2")
	RemoveIpl("id2_14_on_fire")
	RemoveIpl("id2_14_post_no_int")
	RemoveIpl("id2_14_pre_no_int")
	RequestIpl("id2_14_during1")
	RemoveIpl("TrevorsMP")
	RemoveIpl("TrevorsTrailer")
	RequestIpl("TrevorsTrailerTidy")
	RemoveIpl("TrevorsTrailerTrash")
	RemoveIpl("DT1_03_Gr_Closed")
	RemoveIpl("DT1_03_Shutter")
	RequestIpl("yogagame")
	RequestIpl("v_tunnel_hole")
	RequestIpl("V_Michael")
	RequestIpl("V_Michael_Garage")
	RequestIpl("V_Michael_FameShame")
	RequestIpl("V_Michael_JewelHeist")
	RequestIpl("V_Michael_plane_ticket")
	RequestIpl("V_Michael_Scuba")
	RemoveIpl("smboat")
	RequestIpl("hei_yacht_heist")
	RequestIpl("hei_yacht_heist_Bar")
	RequestIpl("hei_yacht_heist_Bedrm")
	RequestIpl("hei_yacht_heist_Bridge")
	RequestIpl("hei_yacht_heist_DistantLights")
	RequestIpl("hei_yacht_heist_enginrm")
	RequestIpl("hei_yacht_heist_LODLights")
	RequestIpl("hei_yacht_heist_Lounge")
	RequestIpl("cargoship")
	RemoveIpl("sp1_10_fake_interior")
	RemoveIpl("sp1_10_fake_interior_lod")
	RequestIpl("SC1_01_NewBill")
	RequestIpl("hw1_02_newbill")
	RequestIpl("hw1_emissive_newbill")
	RequestIpl("sc1_14_newbill")
	RequestIpl("dt1_17_newbill")
	RequestIpl("SC1_01_OldBill")
	RequestIpl("SC1_30_Keep_Closed")
	RequestIpl("refit_unload")
	RequestIpl("post_hiest_unload")
	RequestIpl("occl_meth_grp1")
	RequestIpl("Michael_premier")
	RemoveIpl("DT1_05_HC_REMOVE")
	RequestIpl("DT1_05_HC_REQ")
	RequestIpl("DT1_05_REQUEST")
	RemoveIpl("jewel2fake")
	RemoveIpl("bh1_16_refurb")
	RemoveIpl("ch1_02_closed")
	RemoveIpl("scafstartimap")
	RequestIpl("scafendimap")
	RemoveIpl("bh1_16_doors_shut")
	RequestIpl("ferris_finale_Anim")
	RequestIpl("CS2_06_TriAf02")
	RemoveIpl("CS3_07_MPGates")
	RequestIpl("CS4_08_TriAf02")
	RequestIpl("CS4_04_TriAf03")
	RequestIpl("AP1_04_TriAf01")
	RequestIpl("gr_case0_bunkerclosed")
	RequestIpl("gr_case1_bunkerclosed")
	RequestIpl("gr_case2_bunkerclosed")
	RequestIpl("gr_case3_bunkerclosed")
	RequestIpl("gr_case4_bunkerclosed")
	RequestIpl("gr_case5_bunkerclosed")
	RequestIpl("gr_case6_bunkerclosed")
	RequestIpl("gr_case7_bunkerclosed")
	RequestIpl("gr_case9_bunkerclosed")
	RequestIpl("gr_case10_bunkerclosed")
	RequestIpl("gr_case11_bunkerclosed")
	RequestIpl("cs5_4_trains")
	RequestIpl("chophillskennel")
	RequestIpl("bnkheist_apt_dest")
	RequestIpl("bnkheist_apt_norm")
	RequestIpl("redcarpet")
	RequestIpl("hei_sm_16_interior_v_bahama_milo_")
	RequestIpl("cs3_05_water_grp1")
	RequestIpl("cs3_05_water_grp1_lod")
	RequestIpl("cs3_05_water_grp2")
	RequestIpl("cs3_05_water_grp2_lod")
	RequestIpl("canyonriver01")
	RequestIpl("railing_start")
	RemoveIpl("canyonriver01_traincrash")
	RemoveIpl("railing_end")
	RequestIpl("bh1_47_joshhse_unburnt")
	RequestIpl("bh1_47_joshhse_unburnt_lod")
	RequestIpl("bkr_bi_hw1_13_int")
	RequestIpl("CanyonRvrShallow")
	RequestIpl("methtrailer_grp1")
	RequestIpl("lr_cs6_08_grave_closed")
	RequestIpl("bkr_bi_id1_23_door")
	RemoveIpl("ch1_02_open")
	RequestIpl("sp1_10_real_interior")
	RequestIpl("sp1_10_real_interior_lod")
	RequestIpl("Carwash_with_spinners")
	RemoveIpl("apa_v_mp_h_01_a")
	RemoveIpl("apa_v_mp_h_06_b")
	RemoveIpl("apa_v_mp_h_08_c")
	RemoveIpl("ex_dt1_02_office_01c")
	RemoveIpl("ex_dt1_11_office_01b")
	RemoveIpl("ex_sm_13_office_01a")
	RemoveIpl("ex_sm_15_office_02b")
	RequestIpl("ex_sm_13_office_02a")
	RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
	RequestIpl("bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware02_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware03_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware04_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware05_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_3_biker_dlc_int_ware02_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_4_biker_dlc_int_ware03_milo")
	RemoveIpl("bkr_biker_interior_placement_interior_5_biker_dlc_int_ware04_milo")
	RequestIpl("bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo")
	RemoveIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo")
	RemoveIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo")
	RemoveIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo")
	RemoveIpl("imp_impexp_interior_placement_interior_1_impexp")
	RemoveIpl("imp_impexp_interior_placement")
	RemoveIpl("imp_impexp_interior_placement_interior_0_impexp_int_01_milo_")
	RemoveIpl("imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_")
	RemoveIpl("imp_impexp_interior_placement_interior_2_imptexp_mod_int_01_milo_")
	RemoveIpl("imp_impexp_interior_placement_interior_3_impexp_int_02_milo_")
	RemoveIpl("gr_entrance_placement")
	RemoveIpl("gr_grdlc_interior_placement")
	RemoveIpl("gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_")
	RemoveIpl("gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_")
	RemoveIpl("ch3_rd2_bishopschickengraffiti")
	RemoveIpl("cs5_04_mazebillboardgraffiti")
	RemoveIpl("cs5_roads_ronoilgraffiti")
	RequestIpl("ba_barriers_case0")
	RequestIpl("ba_case0_forsale")
	RequestIpl("ba_case0_dixon")
	RequestIpl("ba_case0_madonna")
	RequestIpl("ba_case0_solomun")
	RequestIpl("ba_case0_taleofus")
	RequestIpl("ba_barriers_case1")
	RequestIpl("ba_case1_forsale")
	RequestIpl("ba_case1_dixon")
	RequestIpl("ba_case1_madonna")
	RequestIpl("ba_case1_solomun")
	RequestIpl("ba_case1_taleofus")
	RequestIpl("ba_barriers_case2")
	RequestIpl("ba_case2_forsale")
	RequestIpl("ba_case2_dixon")
	RequestIpl("ba_case2_madonna")
	RequestIpl("ba_case2_solomun")
	RequestIpl("ba_case2_taleofus")
	RequestIpl("ba_barriers_case3")
	RequestIpl("ba_case3_forsale")
	RequestIpl("ba_case3_dixon")
	RequestIpl("ba_case3_madonna")
	RequestIpl("ba_case3_solomun")
	RequestIpl("ba_case3_taleofus")
	RequestIpl("ba_barriers_case4")
	RequestIpl("ba_case4_forsale")
	RequestIpl("ba_case4_dixon")
	RequestIpl("ba_case4_madonna")
	RequestIpl("ba_case4_solomun")
	RequestIpl("ba_case4_taleofus")
	RequestIpl("ba_barriers_case5")
	RequestIpl("ba_case5_forsale")
	RequestIpl("ba_case5_dixon")
	RequestIpl("ba_case5_madonna")
	RequestIpl("ba_case5_solomun")
	RequestIpl("ba_case5_taleofus")
	RequestIpl("ba_barriers_case6")
	RequestIpl("ba_case6_forsale")
	RequestIpl("ba_case6_dixon")
	RequestIpl("ba_case6_madonna")
	RequestIpl("ba_case6_solomun")
	RequestIpl("ba_case6_taleofus")
	RequestIpl("ba_barriers_case7")
	RequestIpl("ba_case7_forsale")
	RequestIpl("ba_case7_dixon")
	RequestIpl("ba_case7_madonna")
	RequestIpl("ba_case7_solomun")
	RequestIpl("ba_case7_taleofus")
	RequestIpl("ba_barriers_case8")
	RequestIpl("ba_case8_forsale")
	RequestIpl("ba_case8_dixon")
	RequestIpl("ba_case8_madonna")
	RequestIpl("ba_case8_solomun")
	RequestIpl("ba_case8_taleofus")
	RequestIpl("ba_barriers_case9")
	RequestIpl("ba_case9_forsale")
	RequestIpl("ba_case9_dixon")
	RequestIpl("ba_case9_madonna")
	RequestIpl("ba_case9_solomun")
	RequestIpl("ba_case9_taleofus")
	RequestIpl("gr_grdlc_yacht_lod")
	RequestIpl("gr_grdlc_yacht_placement")
	RequestIpl("gr_heist_yacht2")
	RequestIpl("gr_heist_yacht2_bar")
	RequestIpl("gr_heist_yacht2_bar_lod")
	RequestIpl("gr_heist_yacht2_bedrm")
	RequestIpl("gr_heist_yacht2_bedrm_lod")
	RequestIpl("gr_heist_yacht2_bridge")
	RequestIpl("gr_heist_yacht2_bridge_lod")
	RequestIpl("gr_heist_yacht2_enginrm")
	RequestIpl("gr_heist_yacht2_enginrm_lod")
	RequestIpl("gr_heist_yacht2_lod")
	RequestIpl("gr_heist_yacht2_lounge")
	RequestIpl("gr_heist_yacht2_lounge_lod")
	RequestIpl("gr_heist_yacht2_slod")
	RequestIpl("ex_dt1_02_office_02b")
	RequestIpl("ex_dt1_11_office_02c")
	RequestIpl("ex_sm_15_office_01a")
end)

CreateThread(function()

	--DisneyAllsuell
	RequestIpl("DisneyAllsuell_01")
	RequestIpl("DisneyAllsuell_02")
	RequestIpl("DisneyAllsuell_03")
	RequestIpl("DisneyAllsuell_04")
	RequestIpl("DisneyAllsuell_05")
	RequestIpl("DisneyAllsuell_06")
	RequestIpl("DisneyAllsuell_07")
	RequestIpl("DisneyAllsuell_08")
	RequestIpl("DisneyAllsuell_09")
	RequestIpl("DisneyAllsuell_10")
	RequestIpl("DisneyAllsuell_12")
	RequestIpl("DisneyAllsuell_13")
	RequestIpl("DisneyAllsuell_14")
	RequestIpl("DisneyAllsuell_15")
	RequestIpl("DisneyAllsuell_16")
	RequestIpl("DisneyAllsuell_17")
	RequestIpl("DisneyAllsuell_18")
	RequestIpl("DisneyAllsuell_19")
	RequestIpl("DisneyAllsuell_20")
	RequestIpl("DisneyAllsuell_21")

	--DisneyFamilies
	RequestIpl("DisneyFamilies_01")
	RequestIpl("DisneyFamilies_02")
	RequestIpl("DisneyFamilies_03")
	RequestIpl("DisneyFamilies_04")
	RequestIpl("DisneyFamilies_05")
	RequestIpl("DisneyFamilies_06")
	RequestIpl("DisneyFamilies_07")
	RequestIpl("DisneyFamilies_08")
	RequestIpl("DisneyFamilies_09")
	RequestIpl("DisneyFamilies_10")
	RequestIpl("DisneyFamilies_11")
	RequestIpl("DisneyFamilies_12")
	RequestIpl("DisneyFamilies_13")
	RequestIpl("DisneyFamilies_14")
	RequestIpl("DisneyFamilies_15")

	--DisneyForthills
	RequestIpl("DisneyForthills_01")
	RequestIpl("DisneyForthills_02")
	RequestIpl("DisneyForthills_03")
	RequestIpl("DisneyForthills_04")
	RequestIpl("DisneyForthills_05")
	RequestIpl("DisneyForthills_06")
	RequestIpl("DisneyForthills_07")
	RequestIpl("DisneyForthills_08")
	RequestIpl("DisneyForthills_09")
	RequestIpl("DisneyForthills_10")
	RequestIpl("DisneyForthills_11")
	RequestIpl("DisneyForthills_12")
	RequestIpl("DisneyForthills_13")
	RequestIpl("DisneyForthills_14")
	RequestIpl("DisneyForthills_15")
	RequestIpl("DisneyForthills_16")
	RequestIpl("DisneyForthills_17")
	RequestIpl("DisneyForthills_18")
	RequestIpl("DisneyForthills_19")		
	RequestIpl("DisneyForthills_20")
	RequestIpl("DisneyForthills_21")
	RequestIpl("DisneyForthills_22")
	RequestIpl("DisneyForthills_23")
	RequestIpl("DisneyForthills_24")
	RequestIpl("DisneyForthills_25")
	RequestIpl("DisneyForthills_26")
	RequestIpl("DisneyForthills_27")
	RequestIpl("DisneyForthills_28")
	RequestIpl("DisneyForthills_29")		
	RequestIpl("DisneyForthills_30")
	RequestIpl("DisneyForthills_31")
	RequestIpl("DisneyForthills_32")
	RequestIpl("DisneyForthills_33")
	RequestIpl("DisneyForthills_34")
	RequestIpl("DisneyForthills_35")
	RequestIpl("DisneyForthills_36")
	RequestIpl("DisneyForthills_37")
	RequestIpl("DisneyForthills_38")
	RequestIpl("DisneyForthills_39")		
	RequestIpl("DisneyForthills_40")
	RequestIpl("DisneyForthills_41")
	RequestIpl("DisneyForthills_42")
	RequestIpl("DisneyForthills_43")
	RequestIpl("DisneyForthills_44")
	RequestIpl("DisneyForthills_45")
	RequestIpl("DisneyForthills_46")
	RequestIpl("DisneyForthills_47")
	RequestIpl("DisneyForthills_48")
	RequestIpl("DisneyForthills_49")		
	RequestIpl("DisneyForthills_50")
	RequestIpl("DisneyForthills_51")
	RequestIpl("DisneyForthills_52")
	RequestIpl("DisneyForthills_53")
	RequestIpl("DisneyForthills_54")
	RequestIpl("DisneyForthills_55")
	RequestIpl("DisneyForthills_56")
	RequestIpl("DisneyForthills_57")
	RequestIpl("DisneyForthills_58")
	RequestIpl("DisneyForthills_59")		
	RequestIpl("DisneyForthills_60")
	RequestIpl("DisneyForthills_61")
	RequestIpl("DisneyForthills_62")
	RequestIpl("DisneyForthills_63")
	RequestIpl("DisneyForthills_64")
	RequestIpl("DisneyForthills_65")
	RequestIpl("DisneyForthills_66")
	RequestIpl("DisneyForthills_67")
	RequestIpl("DisneyForthills_68")
	RequestIpl("DisneyForthills_69")		
	RequestIpl("DisneyForthills_70")
	RequestIpl("DisneyForthills_71")
	RequestIpl("DisneyForthills_72")
	RequestIpl("DisneyForthills_73")
	RequestIpl("DisneyForthills_74")
	RequestIpl("DisneyForthills_75")
	RequestIpl("DisneyForthills_76")
	RequestIpl("DisneyForthills_77")
	RequestIpl("DisneyForthills_78")
	RequestIpl("DisneyForthills_79")		
	RequestIpl("DisneyForthills_80")
	RequestIpl("DisneyForthills_81")
	RequestIpl("DisneyForthills_82")
	RequestIpl("DisneyForthills_83")
	RequestIpl("DisneyForthills_84")
	RequestIpl("DisneyForthills_85")
	RequestIpl("DisneyForthills_86")
	RequestIpl("DisneyForthills_87")
	RequestIpl("DisneyForthills_88")
	RequestIpl("DisneyForthills_89")		
	RequestIpl("DisneyForthills_90")
	RequestIpl("DisneyForthills_91")
	RequestIpl("DisneyForthills_92")
	RequestIpl("DisneyForthills_93")
	RequestIpl("DisneyForthills_94")
	RequestIpl("DisneyForthills_95")
	RequestIpl("DisneyForthills_96")
	RequestIpl("DisneyForthills_97")
	RequestIpl("DisneyForthills_98")
	RequestIpl("DisneyForthills_99")		
	RequestIpl("DisneyForthills_100")

	--DisneyLuxury 
	RequestIpl("DisneyLuxury_01")
	RequestIpl("DisneyLuxury_02")
	RequestIpl("DisneyLuxury_03")
	RequestIpl("DisneyLuxury_04")
	RequestIpl("DisneyLuxury_05")
	RequestIpl("DisneyLuxury_06")
	RequestIpl("DisneyLuxury_07")
	RequestIpl("DisneyLuxury_08")
	RequestIpl("DisneyLuxury_09")
	RequestIpl("DisneyLuxury_10")
	RequestIpl("DisneyLuxury_11")
	RequestIpl("DisneyLuxury_12")
	RequestIpl("DisneyLuxury_13")
	RequestIpl("DisneyLuxury_14")
	RequestIpl("DisneyLuxury_15")
	RequestIpl("DisneyLuxury_16")
	RequestIpl("DisneyLuxury_17")
	RequestIpl("DisneyLuxury_18")
	RequestIpl("DisneyLuxury_19")
	RequestIpl("DisneyLuxury_20")
	RequestIpl("DisneyLuxury_21")
	RequestIpl("DisneyLuxury_22")
	RequestIpl("DisneyLuxury_23")
	RequestIpl("DisneyLuxury_24")
	RequestIpl("DisneyLuxury_25")
	RequestIpl("DisneyLuxury_26")
	RequestIpl("DisneyLuxury_27")
	RequestIpl("DisneyLuxury_28")
	RequestIpl("DisneyLuxury_29")
	RequestIpl("DisneyLuxury_30")
	RequestIpl("DisneyLuxury_31")
	RequestIpl("DisneyLuxury_32")
	RequestIpl("DisneyLuxury_33")
	RequestIpl("DisneyLuxury_34")
	RequestIpl("DisneyLuxury_35")
	RequestIpl("DisneyLuxury_36")
	RequestIpl("DisneyLuxury_37")
	RequestIpl("DisneyLuxury_38")
	RequestIpl("DisneyLuxury_39")
	RequestIpl("DisneyLuxury_40")
	RequestIpl("DisneyLuxury_41")
	RequestIpl("DisneyLuxury_42")
	RequestIpl("DisneyLuxury_43")
	RequestIpl("DisneyLuxury_44")
	RequestIpl("DisneyLuxury_45")
	RequestIpl("DisneyLuxury_46")
	RequestIpl("DisneyLuxury_47")
	RequestIpl("DisneyLuxury_48")
	RequestIpl("DisneyLuxury_49")
	RequestIpl("DisneyLuxury_50")
	RequestIpl("DisneyLuxury_51")
	RequestIpl("DisneyLuxury_52")
	RequestIpl("DisneyLuxury_53")
	RequestIpl("DisneyLuxury_54")
	RequestIpl("DisneyLuxury_55")
	RequestIpl("DisneyLuxury_56")
	RequestIpl("DisneyLuxury_57")
	RequestIpl("DisneyLuxury_58")
	RequestIpl("DisneyLuxury_59")
	RequestIpl("DisneyLuxury_60")
	RequestIpl("DisneyLuxury_61")
	RequestIpl("DisneyLuxury_62")
	RequestIpl("DisneyLuxury_63")
	RequestIpl("DisneyLuxury_64")
	RequestIpl("DisneyLuxury_65")
	RequestIpl("DisneyLuxury_66")
	RequestIpl("DisneyLuxury_67")
	RequestIpl("DisneyLuxury_68")
	RequestIpl("DisneyLuxury_69")
	RequestIpl("DisneyLuxury_70")		
	RequestIpl("DisneyLuxury_71")	

	--DisneyFranklinGueto
	RequestIpl("DisneyFranklinGueto_01")
	RequestIpl("DisneyFranklinGueto_02")
	RequestIpl("DisneyFranklinGueto_03")
	RequestIpl("DisneyFranklinGueto_04")
	RequestIpl("DisneyFranklinGueto_05")
	RequestIpl("DisneyFranklinGueto_06")
	RequestIpl("DisneyFranklinGueto_07")
	RequestIpl("DisneyFranklinGueto_08")
	RequestIpl("DisneyFranklinGueto_09")
	RequestIpl("DisneyFranklinGueto_10")
	RequestIpl("DisneyFranklinGueto_11")
	RequestIpl("DisneyFranklinGueto_12")
	RequestIpl("DisneyFranklinGueto_13")
	RequestIpl("DisneyFranklinGueto_14")
	RequestIpl("DisneyFranklinGueto_15")
	RequestIpl("DisneyFranklinGueto_16")
	RequestIpl("DisneyFranklinGueto_17")
	RequestIpl("DisneyFranklinGueto_18")
	RequestIpl("DisneyFranklinGueto_19")
	RequestIpl("DisneyFranklinGueto_20")

	--DisneyFranklins
	RequestIpl("DisneyFranklins_01")
	RequestIpl("DisneyFranklins_02")
	RequestIpl("DisneyFranklins_03")
	RequestIpl("DisneyFranklins_04")
	RequestIpl("DisneyFranklins_05")
	RequestIpl("DisneyFranklins_06")
	RequestIpl("DisneyFranklins_07")
	RequestIpl("DisneyFranklins_08")
	RequestIpl("DisneyFranklins_09")
	RequestIpl("DisneyFranklins_10")
	RequestIpl("DisneyFranklins_11")
	RequestIpl("DisneyFranklins_12")
	RequestIpl("DisneyFranklins_13")
	RequestIpl("DisneyFranklins_14")
	RequestIpl("DisneyFranklins_15")
	RequestIpl("DisneyFranklins_16")
	RequestIpl("DisneyFranklins_17")
	RequestIpl("DisneyFranklins_18")
	RequestIpl("DisneyFranklins_19")
	RequestIpl("DisneyFranklins_20")
	RequestIpl("DisneyFranklins_21")
	RequestIpl("DisneyFranklins_22")
	RequestIpl("DisneyFranklins_23")
	RequestIpl("DisneyFranklins_24")
	RequestIpl("DisneyFranklins_25")
	RequestIpl("DisneyFranklins_26")
	RequestIpl("DisneyFranklins_27")
	RequestIpl("DisneyFranklins_28")

	--DisneyLostudio
	RequestIpl("DisneyLostudio_01")
	RequestIpl("DisneyLostudio_02")
	RequestIpl("DisneyLostudio_03")
	RequestIpl("DisneyLostudio_04")
	RequestIpl("DisneyLostudio_05")
	RequestIpl("DisneyLostudio_06")
	RequestIpl("DisneyLostudio_07")
	RequestIpl("DisneyLostudio_08")
	RequestIpl("DisneyLostudio_09")
	RequestIpl("DisneyLostudio_10")
	RequestIpl("DisneyLostudio_11")
	RequestIpl("DisneyLostudio_12")
	RequestIpl("DisneyLostudio_13")
	RequestIpl("DisneyLostudio_14")
	RequestIpl("DisneyLostudio_15")
	RequestIpl("DisneyLostudio_16")
	RequestIpl("DisneyLostudio_17")
	RequestIpl("DisneyLostudio_18")
	RequestIpl("DisneyLostudio_19")
	RequestIpl("DisneyLostudio_20")
	RequestIpl("DisneyLostudio_21")
	RequestIpl("DisneyLostudio_22")
	RequestIpl("DisneyLostudio_23")
	RequestIpl("DisneyLostudio_24")
	RequestIpl("DisneyLostudio_25")
	RequestIpl("DisneyLostudio_26")
	RequestIpl("DisneyLostudio_27")
	RequestIpl("DisneyLostudio_28")
	RequestIpl("DisneyLostudio_29")
	RequestIpl("DisneyLostudio_30")
	RequestIpl("DisneyLostudio_31")
	RequestIpl("DisneyLostudio_32")
	RequestIpl("DisneyLostudio_33")
	RequestIpl("DisneyLostudio_34")
	RequestIpl("DisneyLostudio_35")
	RequestIpl("DisneyLostudio_36")
	RequestIpl("DisneyLostudio_37")
	RequestIpl("DisneyLostudio_38")
	RequestIpl("DisneyLostudio_39")
	RequestIpl("DisneyLostudio_40")
	RequestIpl("DisneyLostudio_41")
	RequestIpl("DisneyLostudio_42")
	RequestIpl("DisneyLostudio_43")
	RequestIpl("DisneyLostudio_44")
	RequestIpl("DisneyLostudio_45")
	RequestIpl("DisneyLostudio_46")
	RequestIpl("DisneyLostudio_47")
	RequestIpl("DisneyLostudio_48")
	RequestIpl("DisneyLostudio_49")
	RequestIpl("DisneyLostudio_50")
	RequestIpl("DisneyLostudio_51")
	RequestIpl("DisneyLostudio_52")
	RequestIpl("DisneyLostudio_53")
	RequestIpl("DisneyLostudio_54")
	RequestIpl("DisneyLostudio_55")
	RequestIpl("DisneyLostudio_56")
	RequestIpl("DisneyLostudio_57")
	RequestIpl("DisneyLostudio_58")

	--DisneyMansao
	RequestIpl("DisneyMansao_03")
	RequestIpl("DisneyMansao_04")
	RequestIpl("DisneyMansao_05")
	RequestIpl("DisneyMansao_06")
	RequestIpl("DisneyMansao_07")
	RequestIpl("DisneyMansao_08")
	RequestIpl("DisneyMansao_09")

	--DisneyMidspaz
	RequestIpl("DisneyMidspaz_01")
	RequestIpl("DisneyMidspaz_02")
	RequestIpl("DisneyMidspaz_03")
	RequestIpl("DisneyMidspaz_04")
	RequestIpl("DisneyMidspaz_05")
	RequestIpl("DisneyMidspaz_06")
	RequestIpl("DisneyMidspaz_07")
	RequestIpl("DisneyMidspaz_08")
	RequestIpl("DisneyMidspaz_09")
	RequestIpl("DisneyMidspaz_10")

	--DisneyPaletoBay
	RequestIpl("DisneyPaletoBay_01")
	RequestIpl("DisneyPaletoBay_02")
	RequestIpl("DisneyPaletoBay_03")
	RequestIpl("DisneyPaletoBay_04")
	RequestIpl("DisneyPaletoBay_05")
	RequestIpl("DisneyPaletoBay_06")
	RequestIpl("DisneyPaletoBay_07")
	RequestIpl("DisneyPaletoBay_08")
	RequestIpl("DisneyPaletoBay_09")
	RequestIpl("DisneyPaletoBay_10")
	RequestIpl("DisneyPaletoBay_11")
	RequestIpl("DisneyPaletoBay_12")
	RequestIpl("DisneyPaletoBay_13")
	RequestIpl("DisneyPaletoBay_14")
	RequestIpl("DisneyPaletoBay_15")
	RequestIpl("DisneyPaletoBay_16")
	RequestIpl("DisneyPaletoBay_17")
	RequestIpl("DisneyPaletoBay_18")
	RequestIpl("DisneyPaletoBay_19")
	RequestIpl("DisneyPaletoBay_20")
	RequestIpl("DisneyPaletoBay_21")
	RequestIpl("DisneyPaletoBay_22")
	RequestIpl("DisneyPaletoBay_23")
	RequestIpl("DisneyPaletoBay_24")
	RequestIpl("DisneyPaletoBay_25")
	RequestIpl("DisneyPaletoBay_26")
	RequestIpl("DisneyPaletoBay_27")
	RequestIpl("DisneyPaletoBay_28")
	RequestIpl("DisneyPaletoBay_29")
	RequestIpl("DisneyPaletoBay_30")
	RequestIpl("DisneyPaletoBay_31")

	--DisneyPaletoMotel
	RequestIpl("DisneyPaletoMotel_01")
	RequestIpl("DisneyPaletoMotel_02")
	RequestIpl("DisneyPaletoMotel_03")
	RequestIpl("DisneyPaletoMotel_04")
	RequestIpl("DisneyPaletoMotel_05")
	RequestIpl("DisneyPaletoMotel_06")
	RequestIpl("DisneyPaletoMotel_07")
	RequestIpl("DisneyPaletoMotel_08")
	RequestIpl("DisneyPaletoMotel_09")
	RequestIpl("DisneyPaletoMotel_11")
	RequestIpl("DisneyPaletoMotel_12")
	RequestIpl("DisneyPaletoMotel_13")
	RequestIpl("DisneyPaletoMotel_14")
	RequestIpl("DisneyPaletoMotel_15")
	RequestIpl("DisneyPaletoMotel_16")
	RequestIpl("DisneyPaletoMotel_17")
	RequestIpl("DisneyPaletoMotel_18")
	RequestIpl("DisneyPaletoMotel_19")
	RequestIpl("DisneyPaletoMotel_20")
	RequestIpl("DisneyPaletoMotel_21")
	RequestIpl("DisneyPaletoMotel_22")

	--DisneyPinkCageMotel
	RequestIpl("DisneyPinkCageMotel_01")
	RequestIpl("DisneyPinkCageMotel_02")
	RequestIpl("DisneyPinkCageMotel_03")
	RequestIpl("DisneyPinkCageMotel_04")
	RequestIpl("DisneyPinkCageMotel_05")
	RequestIpl("DisneyPinkCageMotel_06")
	RequestIpl("DisneyPinkCageMotel_07")
	RequestIpl("DisneyPinkCageMotel_08")
	RequestIpl("DisneyPinkCageMotel_09")
	RequestIpl("DisneyPinkCageMotel_10")
	RequestIpl("DisneyPinkCageMotel_11")
	RequestIpl("DisneyPinkCageMotel_12")
	RequestIpl("DisneyPinkCageMotel_13")
	RequestIpl("DisneyPinkCageMotel_14")
	RequestIpl("DisneyPinkCageMotel_15")
	RequestIpl("DisneyPinkCageMotel_16")
	RequestIpl("DisneyPinkCageMotel_17")
	RequestIpl("DisneyPinkCageMotel_18")
	RequestIpl("DisneyPinkCageMotel_19")
	RequestIpl("DisneyPinkCageMotel_20")
	RequestIpl("DisneyPinkCageMotel_21")
	RequestIpl("DisneyPinkCageMotel_22")
	RequestIpl("DisneyPinkCageMotel_23")
	RequestIpl("DisneyPinkCageMotel_24")
	RequestIpl("DisneyPinkCageMotel_25")
	RequestIpl("DisneyPinkCageMotel_26")
	RequestIpl("DisneyPinkCageMotel_27")
	RequestIpl("DisneyPinkCageMotel_28")
	RequestIpl("DisneyPinkCageMotel_29")
	RequestIpl("DisneyPinkCageMotel_30")
	RequestIpl("DisneyPinkCageMotel_31")
	RequestIpl("DisneyPinkCageMotel_32")
	RequestIpl("DisneyPinkCageMotel_33")
	RequestIpl("DisneyPinkCageMotel_34")
	RequestIpl("DisneyPinkCageMotel_35")
	RequestIpl("DisneyPinkCageMotel_36")
	RequestIpl("DisneyPinkCageMotel_37")
	RequestIpl("DisneyPinkCageMotel_38")

	--DisneySandyShore
	RequestIpl("DisneySandyShore_01")

	--DisneyVagosHouse
	RequestIpl("DisneyVagosHouse_01")
	RequestIpl("DisneyVagosHouse_02")
	RequestIpl("DisneyVagosHouse_03")
	RequestIpl("DisneyVagosHouse_04")
	RequestIpl("DisneyVagosHouse_05")
	RequestIpl("DisneyVagosHouse_06")
	RequestIpl("DisneyVagosHouse_07")
	RequestIpl("DisneyVagosHouse_08")
	RequestIpl("DisneyVagosHouse_09")
	RequestIpl("DisneyVagosHouse_11")
	RequestIpl("DisneyVagosHouse_12")
	RequestIpl("DisneyVagosHouse_13")
	RequestIpl("DisneyVagosHouse_14")
	RequestIpl("DisneyVagosHouse_15")
	RequestIpl("DisneyVagosHouse_16")
	RequestIpl("DisneyVagosHouse_17")
	RequestIpl("DisneyVagosHouse_18")
	RequestIpl("DisneyVagosHouse_19")
	RequestIpl("DisneyVagosHouse_20")
	RequestIpl("DisneyVagosHouse_21")
	RequestIpl("DisneyVagosHouse_22")
	RequestIpl("DisneyVagosHouse_23")
	RequestIpl("DisneyVagosHouse_24")
	RequestIpl("DisneyVagosHouse_25")
	RequestIpl("DisneyVagosHouse_26")
	RequestIpl("DisneyVagosHouse_27")
	RequestIpl("DisneyVagosHouse_28")
	RequestIpl("DisneyVagosHouse_29")
	RequestIpl("DisneyVagosHouse_30")
	RequestIpl("DisneyVagosHouse_31")
	RequestIpl("DisneyVagosHouse_32")
	RequestIpl("DisneyVagosHouse_33")
	RequestIpl("DisneyVagosHouse_34")
	RequestIpl("DisneyVagosHouse_35")

	--DisneyVagosMotel	
	RequestIpl("DisneyVagosMotel_01")
	RequestIpl("DisneyVagosMotel_02")
	RequestIpl("DisneyVagosMotel_03")
	RequestIpl("DisneyVagosMotel_04")
	RequestIpl("DisneyVagosMotel_05")
	RequestIpl("DisneyVagosMotel_06")
	RequestIpl("DisneyVagosMotel_07")
	RequestIpl("DisneyVagosMotel_08")
	RequestIpl("DisneyVagosMotel_09")
	RequestIpl("DisneyVagosMotel_10")
	RequestIpl("DisneyVagosMotel_11")
	RequestIpl("DisneyVagosMotel_12")
	RequestIpl("DisneyVagosMotel_13")
	RequestIpl("DisneyVagosMotel_14")
	RequestIpl("DisneyVagosMotel_15")
	RequestIpl("DisneyVagosMotel_16")
	RequestIpl("DisneyVagosMotel_17")
	RequestIpl("DisneyVagosMotel_18")
	RequestIpl("DisneyVagosMotel_19")
	RequestIpl("DisneyVagosMotel_20")
	RequestIpl("DisneyVagosMotel_21")
	RequestIpl("DisneyVagosMotel_22")
	RequestIpl("DisneyVagosMotel_23")
	RequestIpl("DisneyVagosMotel_24")
	RequestIpl("DisneyVagosMotel_25")
	RequestIpl("DisneyVagosMotel_26")
	RequestIpl("DisneyVagosMotel_27")
	RequestIpl("DisneyVagosMotel_28")
	RequestIpl("DisneyVagosMotel_29")
	RequestIpl("DisneyVagosMotel_30")
	RequestIpl("DisneyVagosMotel_31")
	RequestIpl("DisneyVagosMotel_32")

	
end)

CreateThread(function()

interiorID = GetInteriorAtCoords(96.47223, 6347.784, 30.48238)
	if IsValidInterior(interiorID) then
	
		EnableInteriorProp(interiorID, "weed_hosea")
		EnableInteriorProp(interiorID, "weed_hoseb")
		EnableInteriorProp(interiorID, "weed_hosec")
		EnableInteriorProp(interiorID, "weed_hosed")
		EnableInteriorProp(interiorID, "weed_hosee")
		EnableInteriorProp(interiorID, "weed_hosef")
		EnableInteriorProp(interiorID, "weed_hoseg")
		EnableInteriorProp(interiorID, "weed_hoseh")
		EnableInteriorProp(interiorID, "weed_hosei")
		EnableInteriorProp(interiorID, "weed_growtha_stage3")
		EnableInteriorProp(interiorID, "weed_growthb_stage3")
		EnableInteriorProp(interiorID, "weed_growthc_stage3")
		EnableInteriorProp(interiorID, "weed_growthd_stage3")
		EnableInteriorProp(interiorID, "weed_growthe_stage3")
		EnableInteriorProp(interiorID, "weed_growthf_stage3")
		EnableInteriorProp(interiorID, "weed_growthg_stage3")
		EnableInteriorProp(interiorID, "weed_growthh_stage3")
		EnableInteriorProp(interiorID, "weed_growthi_stage3")
		EnableInteriorProp(interiorID, "light_growtha_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthb_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthc_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthd_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthe_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthf_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthg_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthh_stage33_upgrade")
		EnableInteriorProp(interiorID, "light_growthi_stage33_upgrade")
		EnableInteriorProp(interiorID, "weed_upgrade_equip")
		EnableInteriorProp(interiorID, "weed_drying")
		EnableInteriorProp(interiorID, "weed_security_upgrade")
		EnableInteriorProp(interiorID, "weed_production")
		EnableInteriorProp(interiorID, "weed_set_up")
		EnableInteriorProp(interiorID, "weed_chairs")
		RefreshInterior(interiorID)
		
	end

interiorID = GetInteriorAtCoords(1129.42,-3196.79,-39.66)
	if IsValidInterior(interiorID) then
		EnableInteriorProp(interiorID, "weed_upgrade_equip")
		EnableInteriorProp(interiorID, "counterfeit_security")
		EnableInteriorProp(interiorID, "counterfeit_cashpile100a")
		EnableInteriorProp(interiorID, "counterfeit_cashpile20a")
		EnableInteriorProp(interiorID, "counterfeit_cashpile10a")
		EnableInteriorProp(interiorID, "counterfeit_cashpile100b")
		EnableInteriorProp(interiorID, "counterfeit_cashpile100c")
		EnableInteriorProp(interiorID, "counterfeit_cashpile100d")
		EnableInteriorProp(interiorID, "counterfeit_cashpile20b")
		EnableInteriorProp(interiorID, "counterfeit_cashpile20c")
		EnableInteriorProp(interiorID, "counterfeit_cashpile20d")
		EnableInteriorProp(interiorID, "counterfeit_cashpile10b")
		EnableInteriorProp(interiorID, "counterfeit_cashpile10c")
		EnableInteriorProp(interiorID, "counterfeit_cashpile10d")
		EnableInteriorProp(interiorID, "counterfeit_setup")
		EnableInteriorProp(interiorID, "counterfeit_upgrade_equip")
		EnableInteriorProp(interiorID, "dryera_on")
		EnableInteriorProp(interiorID, "dryerb_on")
		EnableInteriorProp(interiorID, "dryerc_on")
		EnableInteriorProp(interiorID, "dryerd_on")
		EnableInteriorProp(interiorID, "money_cutter")
		EnableInteriorProp(interiorID, "special_chairs")
		RefreshInterior(interiorID)
	end


interiorID = GetInteriorAtCoords(1497.75100000, 6393.09000000, 21.78359000)
	if IsValidInterior(interiorID) then
		EnableInteriorProp(interiorID, "meth_lab_upgrade")
		EnableInteriorProp(interiorID, "meth_lab_production")
		EnableInteriorProp(interiorID, "meth_lab_security_high")
		EnableInteriorProp(interiorID, "meth_lab_setup")
		EnableInteriorProp(interiorID, "counterfeit_standard_equip")
		RefreshInterior(interiorID)
	end

interiorID = GetInteriorAtCoords(-1103.1722412109,4951.3447265625,234.8638)
	if IsValidInterior(interiorID) then
		EnableInteriorProp(interiorID, "coke_cut_01")
		EnableInteriorProp(interiorID, "coke_cut_02")
		EnableInteriorProp(interiorID, "coke_cut_03")
		EnableInteriorProp(interiorID, "coke_cut_04")
		EnableInteriorProp(interiorID, "coke_cut_05")
		EnableInteriorProp(interiorID, "set_up")
		EnableInteriorProp(interiorID, "security_high")
		EnableInteriorProp(interiorID, "production_upgrade")
		EnableInteriorProp(interiorID, "equipment_upgrade")
		RefreshInterior(interiorID)
	end
end)

-----------------------------------------------------------------------------------------------------------------------------------------
-- IPLLOADER
-----------------------------------------------------------------------------------------------------------------------------------------
CreateThread(function()
	LoadMpDlcMaps()
	EnableMpDlcMaps(1)
	-- ISLAND
	RequestIpl("h4_islandairstrip")
	RequestIpl("h4_islandairstrip_props")
	RequestIpl("h4_islandx_mansion")
	RequestIpl("h4_islandx_mansion_props")
	RequestIpl("h4_islandx_props")
	RequestIpl("h4_islandxdock")
	RequestIpl("h4_islandxdock_props")
	RequestIpl("h4_islandxdock_props_2")
	RequestIpl("h4_islandxtower")
	RequestIpl("h4_islandx_maindock")
	RequestIpl("h4_islandx_maindock_props")
	RequestIpl("h4_islandx_maindock_props_2")
	RequestIpl("h4_IslandX_Mansion_Vault")
	RequestIpl("h4_islandairstrip_propsb")
	RequestIpl("h4_beach")
	RequestIpl("h4_beach_props")
	RequestIpl("h4_beach_bar_props")
	RequestIpl("h4_islandx_barrack_props")
	RequestIpl("h4_islandx_checkpoint")
	RequestIpl("h4_islandx_checkpoint_props")
	RequestIpl("h4_islandx_Mansion_Office")
	RequestIpl("h4_islandx_Mansion_LockUp_01")
	RequestIpl("h4_islandx_Mansion_LockUp_02")
	RequestIpl("h4_islandx_Mansion_LockUp_03")
	RequestIpl("h4_islandairstrip_hangar_props")
	RequestIpl("h4_IslandX_Mansion_B")
	RequestIpl("h4_islandairstrip_doorsclosed")
	RequestIpl("h4_Underwater_Gate_Closed")
	RequestIpl("h4_mansion_gate_closed")
	RequestIpl("h4_aa_guns")
	RequestIpl("h4_IslandX_Mansion_GuardFence")
	RequestIpl("h4_IslandX_Mansion_Entrance_Fence")
	RequestIpl("h4_IslandX_Mansion_B_Side_Fence")
	RequestIpl("h4_IslandX_Mansion_Lights")
	RequestIpl("h4_islandxcanal_props")
	RequestIpl("h4_beach_props_party")
	RequestIpl("h4_islandX_Terrain_props_06_a")
	RequestIpl("h4_islandX_Terrain_props_06_b")
	RequestIpl("h4_islandX_Terrain_props_06_c")
	RequestIpl("h4_islandX_Terrain_props_05_a")
	RequestIpl("h4_islandX_Terrain_props_05_b")
	RequestIpl("h4_islandX_Terrain_props_05_c")
	RequestIpl("h4_islandX_Terrain_props_05_d")
	RequestIpl("h4_islandX_Terrain_props_05_e")
	RequestIpl("h4_islandX_Terrain_props_05_f")
	RequestIpl("H4_islandx_terrain_01")
	RequestIpl("H4_islandx_terrain_02")
	RequestIpl("H4_islandx_terrain_03")
	RequestIpl("H4_islandx_terrain_04")
	RequestIpl("H4_islandx_terrain_05")
	RequestIpl("H4_islandx_terrain_06")
	RequestIpl("h4_ne_ipl_00")
	RequestIpl("h4_ne_ipl_01")
	RequestIpl("h4_ne_ipl_02")
	RequestIpl("h4_ne_ipl_03")
	RequestIpl("h4_ne_ipl_04")
	RequestIpl("h4_ne_ipl_05")
	RequestIpl("h4_ne_ipl_06")
	RequestIpl("h4_ne_ipl_07")
	RequestIpl("h4_ne_ipl_08")
	RequestIpl("h4_ne_ipl_09")
	RequestIpl("h4_nw_ipl_00")
	RequestIpl("h4_nw_ipl_01")
	RequestIpl("h4_nw_ipl_02")
	RequestIpl("h4_nw_ipl_03")
	RequestIpl("h4_nw_ipl_04")
	RequestIpl("h4_nw_ipl_05")
	RequestIpl("h4_nw_ipl_06")
	RequestIpl("h4_nw_ipl_07")
	RequestIpl("h4_nw_ipl_08")
	RequestIpl("h4_nw_ipl_09")
	RequestIpl("h4_se_ipl_00")
	RequestIpl("h4_se_ipl_01")
	RequestIpl("h4_se_ipl_02")
	RequestIpl("h4_se_ipl_03")
	RequestIpl("h4_se_ipl_04")
	RequestIpl("h4_se_ipl_05")
	RequestIpl("h4_se_ipl_06")
	RequestIpl("h4_se_ipl_07")
	RequestIpl("h4_se_ipl_08")
	RequestIpl("h4_se_ipl_09")
	RequestIpl("h4_sw_ipl_00")
	RequestIpl("h4_sw_ipl_01")
	RequestIpl("h4_sw_ipl_02")
	RequestIpl("h4_sw_ipl_03")
	RequestIpl("h4_sw_ipl_04")
	RequestIpl("h4_sw_ipl_05")
	RequestIpl("h4_sw_ipl_06")
	RequestIpl("h4_sw_ipl_07")
	RequestIpl("h4_sw_ipl_08")
	RequestIpl("h4_sw_ipl_09")
	RequestIpl("h4_islandx_mansion")
	RequestIpl("h4_islandxtower_veg")
	RequestIpl("h4_islandx_sea_mines")
	RequestIpl("h4_islandx")
	RequestIpl("h4_islandx_barrack_hatch")
	RequestIpl("h4_islandxdock_water_hatch")
	RequestIpl("h4_beach_party")
	SetDeepOceanScaler(0.0)
end)

-----------------------------------------------------------------------------------------------------------------------------------------
-- IPLOADER
-----------------------------------------------------------------------------------------------------------------------------------------
CreateThread(function()
	LoadInterior(GetInteriorAtCoords(313.36,-591.02,43.29))
	LoadInterior(GetInteriorAtCoords(440.84,-983.14,30.69))
	LoadInterior(GetInteriorAtCoords(1768.09,3327.09,41.45))

	for _,v in pairs(allIpls) do
		loadInt(v.coords,v.interiorsProps)
	end
end)

function loadInt(coordsTable,table)
	for _,v in pairs(coordsTable) do
		local interior = GetInteriorAtCoords(v[1],v[2],v[3])
		LoadInterior(interior)
		for _,i in pairs(table) do
			EnableInteriorProp(interior,i)
			Wait(10)
		end
		RefreshInterior(interior)
	end
end

allIpls = {
	{
		interiorsProps = {
			"swap_clean_apt",
			"layer_debra_pic",
			"layer_whiskey",
			"swap_sofa_A"
		},
		coords = {{ -1150.7,-1520.7,10.6 }}
	},{
		interiorsProps = {
			"csr_beforeMission",
			"csr_inMission"
		},
		coords = {{ -47.1,-1115.3,26.5 }}
	},{
		interiorsProps = {
			"V_Michael_bed_tidy",
			"V_Michael_M_items",
			"V_Michael_D_items",
			"V_Michael_S_items",
			"V_Michael_L_Items"
		},
		coords = {{ -802.3,175.0,72.8 }}
	},{
		interiorsProps = {
			"meth_lab_production",
			"meth_lab_upgrade",
			"meth_lab_setup"
		},
		coords = {{ 38.49,3714.1,11.01 }}
	}--,{
		--interiorsProps = {
		--	"branded_style_set",
		--	"car_floor_hatch"
		--},
		--coords = {{ 941.00,-972.66,39.14 }}
	--}
}